networks:
  microservices-net:
    external: true

volumes:
  erpnext_sites:
    external: true
  erpnext_logs:
    external: true

services:
  erpnext-websocket:
    container_name: erpnext-websocket
    image: frappe/erpnext:latest
    restart: unless-stopped
    networks:
      - microservices-net
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: redis://redis:6379
      FRAPPE_REDIS_QUEUE: redis://redis:6379
    volumes:
      - erpnext_sites:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
