networks:
  microservices-net:
    external: true

volumes:
  erpnext_sites:
    external: true
  erpnext_logs:
    external: true

services:
  erpnext-frontend:
    container_name: erpnext-frontend
    image: frappe/erpnext:latest
    restart: unless-stopped
    networks:
      - microservices-net
    depends_on:
      - erpnext-websocket
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: erpnext-backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: erpnext-websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - erpnext_sites:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    ports:
      - "127.0.0.1:8900:8080"
