networks:
  microservices-net:
    external: true

services:
  krakend:
    image: devopsfaith/krakend:2.6
    container_name: krakend
    command: ["run", "-c", "/etc/krakend/krakend.json"]
    volumes:
      - ../../config/krakend/krakend.json:/etc/krakend/krakend.json:ro
    ports:
      - "127.0.0.1:4000:8080"
    networks:
      - microservices-net

  krakend-designer:
    image: devopsfaith/krakendesigner:latest
    container_name: krakend-designer
    volumes:
      - ../../config/krakend:/etc/krakend
    ports:
      - "127.0.0.1:4006:80"
    networks:
      - microservices-net