networks:
  microservices-net:
    external: true

services:
  krakend:
    image: devopsfaith/krakend:2.6
    container_name: krakend
    command: ["run", "-c", "/etc/krakend/krakend.json"]
    volumes:
      - ../../config/krakend/krakend.json:/etc/krakend/krakend.json:ro
    ports:
      - "8080:8080"
    networks:
      - microservices-net