networks:
  microservices-net:
    external: true

services:
  krakend-designer:
    image: devopsfaith/krakendesigner:latest
    container_name: krakend-designer
    volumes:
      - ../../config/krakend:/etc/krakend
    ports:
      - "127.0.0.1:4006:80"
    networks:
      - microservices-net