networks:
  microservices-net:
    external: true

volumes:
  localstack_data:

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - SERVICES=s3,sqs,sns,dynamodb,lambda,apigateway,cloudwatch,logs,events,secretsmanager
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost.localstack.cloud
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "127.0.0.1:9520:4566"
      - "127.0.0.1:9521:4571"
    volumes:
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
