networks:
  microservices-net:
    external: true

volumes:
  seaweedfs_filer:

services:
  seaweedfs-filer:
    container_name: seaweedfs-filer
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    env_file: ../../.env
    command: filer -master=seaweedfs-master:9333 -ip=seaweedfs-filer
    ports:
      - "127.0.0.1:9512:8888"
    volumes:
      - seaweedfs_filer:/data
    networks:
      - microservices-net
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/"]
      interval: 30s
      timeout: 10s
      retries: 3
