version: '3.8'

networks:
  microservices-net:
    external: true

volumes:
  mariadb_data:

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "127.0.0.1:8501:3306"  # Local access to MariaDB
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - microservices-net