networks:
  microservices-net:
    external: true

volumes:
  mariadb_data:

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8501:3306"  # Local access to MariaDB
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - microservices-net