networks:
  microservices-net:
    external: true

services:
  memcached:
    container_name: memcached
    image: memcached:alpine
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - MEMCACHED_CACHE_SIZE=256
      - MEMCACHED_MAX_CONNECTIONS=1024
      - MEMCACHED_THREADS=4
    ports:
      - "127.0.0.1:11211:11211"
    command: 
      - "memcached"
      - "-m"
      - "256"
      - "-c"
      - "1024"
      - "-t"
      - "4"
      - "-v"
      - "-I"
      - "4m"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Memcached admin interface
  memcached-admin:
    container_name: memcached-admin
    image: bastienm/phpmemcacheadmin:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - MEMCACHE_HOST=memcached
      - MEMCACHE_PORT=11211
    ports:
      - "127.0.0.1:8092:80"
    networks:
      - microservices-net
    depends_on:
      - memcached
