networks:
  microservices-net:
    external: true

volumes:
  mongodb_data:
  mongodb_dump:

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8503:27017" # Local access to MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongodb_data:/data/db
      - mongodb_dump:/dump
    networks:
      - microservices-net
