networks:
  microservices-net:
    external: true

volumes:
  mssql_data:

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "127.0.0.1:8506:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - microservices-net