version: "3.8"

networks:
  microservices-net:
    external: true

volumes:
  mysql_data:

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8505:3306"  # Local access to MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - microservices-net