networks:
  microservices-net:
    external: true

volumes:
  mysql_data:

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - MYSQL_DATABASE=mysqldb_user
      - MYSQL_USER=mysql_user
      - MYSQL_ROOT_PASSWORD=${SHARED_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${SHARED_DB_PASSWORD}
    ports:
      - "127.0.0.1:8505:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-net