networks:
  microservices-net:
    external: true

volumes:
  neo4j_data:
  neo4j_logs:

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - NEO4J_AUTH=neo4j/admin1234567
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "admin1234567", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3
