networks:
  microservices-net:
    external: true

volumes:
  postgres_data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_MULTIPLE_DATABASES=postgres,metabase,nocodb,openproject
      - POSTGRES_PASSWORD=admin1234567
    ports:
      - "127.0.0.1:8502:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net