networks:
  microservices-net:
    external: true

volumes:
  postgres_data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8502:5432" # Local access to PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net
