networks:
  microservices-net:
    external: true

volumes:
  redis_data:

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:8504:6379" # Local access to Redis
    volumes:
      - redis_data:/data
    networks:
      - microservices-net
