networks:
  microservices-net:
    external: true

volumes:
  redis_data:

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8504:6379"
    command: redis-server --requirepass ${SHARED_DB_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - microservices-net