services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
    - 127.0.0.1:8506:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Devarch123!
    volumes:
    - mssql_data:/var/opt/mssql
    healthcheck:
      test:
      - CMD-SHELL
      - /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}"
        -Q "SELECT 1" -C -b
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
    - microservices-net
    container_name: mssql
volumes:
  mssql_data: null
networks:
  microservices-net:
    external: true
