networks:
  microservices-net:
    external: true

volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    env_file: ../../.env
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - "127.0.0.1:8929:8929"
      - "127.0.0.1:2224:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8929/-/health"]
      interval: 60s
      timeout: 30s
      retries: 5
