# compose/project-management/openproject.yml
networks:
  microservices-net:
    external: true

volumes:
  openproject_data:

services:
  openproject-web:
    container_name: openproject-web
    image: openproject/openproject:16-slim
    restart: unless-stopped
    env_file: ../../.env
    environment:
      # Basic Configuration
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_HOST__NAME=openproject.test

      # Database Configuration
      - DATABASE_URL=postgres://postgres:${SHARED_DB_PASSWORD}@postgres:5432/openproject?pool=20&encoding=unicode&reconnect=true

      # Cache Configuration (Redis)
      - RAILS_CACHE_STORE=redis_cache_store
      - OPENPROJECT_CACHE__REDIS__URL=redis://redis:6379/2

      # Performance Settings
      - RAILS_MIN_THREADS=4
      - RAILS_MAX_THREADS=16
      - WEB__WORKERS=2
      - WEB__TIMEOUT=120

      # SMTP Configuration (using your existing Mailpit)
      - EMAIL_DELIVERY_METHOD=smtp
      - SMTP_ADDRESS=mailpit
      - SMTP_PORT=1025
      - SMTP_DOMAIN=${DOMAIN_SUFFIX}
      - SMTP_AUTHENTICATION=none
      - SMTP_ENABLE_STARTTLS_AUTO=false
      - OPENPROJECT_MAIL__FROM=noreply@${DOMAIN_SUFFIX}

      # Admin User Creation (Seed Variables)
      - OPENPROJECT_SEED__ADMIN__USER__NAME=${ADMIN_USER}
      - OPENPROJECT_SEED__ADMIN__USER__MAIL=${ADMIN_EMAIL}
      - OPENPROJECT_SEED__ADMIN__USER__PASSWORD=${ADMIN_PASSWORD}
      - OPENPROJECT_SEED__ADMIN__USER__PASSWORD__RESET=false

      # Security & Features
      - OPENPROJECT_DISABLE__BROWSER__CACHE=true
      - OPENPROJECT_HSTS=false
      - OPENPROJECT_SECURITY__BADGE__DISPLAYED=false
    command: "./docker/prod/web"
    ports:
      - "127.0.0.1:8090:8080"
    volumes:
      - openproject_data:/var/openproject/assets
    networks:
      - microservices-net
    depends_on:
      - openproject-seeder
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health_checks/default"]
      interval: 30s
      timeout: 10s
      retries: 3

  openproject-worker:
    container_name: openproject-worker
    image: openproject/openproject:16-slim
    restart: unless-stopped
    env_file: ../../.env
    environment:
      # Basic Configuration
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_HOST__NAME=openproject.test

      # Database Configuration
      - DATABASE_URL=postgres://postgres:${SHARED_DB_PASSWORD}@postgres:5432/openproject?pool=20&encoding=unicode&reconnect=true

      # Cache Configuration
      - RAILS_CACHE_STORE=redis_cache_store
      - OPENPROJECT_CACHE__REDIS__URL=redis://redis:6379/2

      # SMTP Configuration
      - EMAIL_DELIVERY_METHOD=smtp
      - SMTP_ADDRESS=mailpit
      - SMTP_PORT=1025
      - SMTP_DOMAIN=${DOMAIN_SUFFIX}
      - SMTP_AUTHENTICATION=none
      - SMTP_ENABLE_STARTTLS_AUTO=false
      - OPENPROJECT_MAIL__FROM=noreply@${DOMAIN_SUFFIX}
    command: "./docker/prod/worker"
    volumes:
      - openproject_data:/var/openproject/assets
    networks:
      - microservices-net
    depends_on:
      - openproject-seeder

  openproject-seeder:
    container_name: openproject-seeder
    image: openproject/openproject:16-slim
    restart: on-failure
    env_file: ../../.env
    environment:
      # Basic Configuration
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_HOST__NAME=openproject.test

      # Database Configuration
      - DATABASE_URL=postgres://postgres:${SHARED_DB_PASSWORD}@postgres:5432/openproject?pool=20&encoding=unicode&reconnect=true

      # Cache Configuration
      - RAILS_CACHE_STORE=redis_cache_store
      - OPENPROJECT_CACHE__REDIS__URL=redis://redis:6379/2

      # Admin User Creation (Primary location for seed variables)
      - OPENPROJECT_SEED__ADMIN__USER__NAME=${ADMIN_USER}
      - OPENPROJECT_SEED__ADMIN__USER__MAIL=${ADMIN_EMAIL}
      - OPENPROJECT_SEED__ADMIN__USER__PASSWORD=${ADMIN_PASSWORD}
      - OPENPROJECT_SEED__ADMIN__USER__PASSWORD__RESET=false
    command: "./docker/prod/seeder"
    volumes:
      - openproject_data:/var/openproject/assets
    networks:
      - microservices-net

  openproject-cron:
    container_name: openproject-cron
    image: openproject/openproject:16-slim
    restart: unless-stopped
    env_file: ../../.env
    environment:
      # Basic Configuration
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_HOST__NAME=openproject.test

      # Database Configuration
      - DATABASE_URL=postgres://postgres:${SHARED_DB_PASSWORD}@postgres:5432/openproject?pool=20&encoding=unicode&reconnect=true

      # Cache Configuration
      - RAILS_CACHE_STORE=redis_cache_store
      - OPENPROJECT_CACHE__REDIS__URL=redis://redis:6379/2

      # SMTP Configuration
      - EMAIL_DELIVERY_METHOD=smtp
      - SMTP_ADDRESS=mailpit
      - SMTP_PORT=1025
      - SMTP_DOMAIN=${DOMAIN_SUFFIX}
      - SMTP_AUTHENTICATION=none
      - SMTP_ENABLE_STARTTLS_AUTO=false
      - OPENPROJECT_MAIL__FROM=noreply@${DOMAIN_SUFFIX}
    command: "./docker/prod/cron"
    volumes:
      - openproject_data:/var/openproject/assets
    networks:
      - microservices-net
    depends_on:
      - openproject-seeder
