networks:
  microservices-net:
    external: true

volumes:
  concourse_keys:
  concourse_worker:

services:
  concourse-worker:
    container_name: concourse-worker
    image: concourse/concourse:latest
    restart: unless-stopped
    command: worker
    privileged: true
    env_file: ../../.env
    environment:
      - CONCOURSE_TSA_HOST=concourse-web:2222
      - CONCOURSE_WORKER_KEY=/concourse-keys/worker_key
      - CONCOURSE_TSA_PUBLIC_KEY=/concourse-keys/tsa_host_key.pub
      - CONCOURSE_TSA_WORKER_PRIVATE_KEY=/concourse-keys/worker_key
      - CONCOURSE_GARDEN_NETWORK_POOL=10.254.0.0/16
      - CONCOURSE_BAGGAGECLAIM_DRIVER=overlay
    volumes:
      - concourse_keys:/concourse-keys
      - concourse_worker:/opt/concourse/worker
    networks:
      - microservices-net
    depends_on:
      - concourse-web
