networks:
  microservices-net:
    external: true

volumes:
  gitlab_runner_config:

services:
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "127.0.0.1:9630:9252"
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-net
