networks:
  microservices-net:
    external: true

volumes:
  jenkins_home:

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "127.0.0.1:9600:8080"
      - "127.0.0.1:9601:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - microservices-net
    user: root
