networks:
  microservices-net:
    external: true

volumes:
  drone_data:

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID:-}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET:-}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET:-secret}
      - DRONE_SERVER_HOST=localhost:9610
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:admin,admin:true
      - DRONE_LOGS_DEBUG=true
    ports:
      - "127.0.0.1:9610:80"
    volumes:
      - drone_data:/data
    networks:
      - microservices-net
