networks:
  microservices-net:
    external: true

volumes:
  woodpecker_data:

services:
  woodpecker-server:
    container_name: woodpecker-server
    image: woodpeckerci/woodpecker-server:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://localhost:9620
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://gitea:3000
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT:-}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET:-}
      - WOODPECKER_ADMIN=admin
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET:-secret}
    ports:
      - "127.0.0.1:9620:8000"
    volumes:
      - woodpecker_data:/var/lib/woodpecker
    networks:
      - microservices-net
