networks:
  microservices-net:
    external: true

services:
  woodpecker-agent:
    container_name: woodpecker-agent
    image: woodpeckerci/woodpecker-agent:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET:-secret}
      - WOODPECKER_MAX_WORKFLOWS=4
      - WOODPECKER_BACKEND=docker
    ports:
      - "127.0.0.1:9621:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-net
    depends_on:
      - woodpecker-server
