services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2
    restart: unless-stopped
    ports:
    - 127.0.0.1:81:81
    - 127.0.0.1:80:80
    - 127.0.0.1:443:443
    volumes:
    - npm_data:/data
    - npm_letsencrypt:/etc/letsencrypt
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:81/api/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
    - microservices-net
    x-devarch-config:
      custom/events.conf: /data/nginx/custom/events.conf
      custom/http.conf: /data/nginx/custom/http.conf
      custom/http_top.conf: /data/nginx/custom/http_top.conf
      custom/root_top.conf: /data/nginx/custom/root_top.conf
      custom/server_proxy.conf: /data/nginx/custom/server_proxy.conf
      certs/local.crt: /etc/ssl/certs/local.crt
      certs/local.key: /etc/ssl/private/local.key
    container_name: nginx-proxy-manager
volumes:
  npm_data: null
  npm_letsencrypt: null
networks:
  microservices-net:
    external: true
