networks:
  microservices-net:
    external: true

volumes:
  erpnext_sites:
    external: true
  erpnext_logs:
    external: true

services:
  erpnext-scheduler:
    container_name: erpnext-scheduler
    image: frappe/erpnext:latest
    restart: unless-stopped
    networks:
      - microservices-net
    command:
      - bench
      - schedule
    volumes:
      - erpnext_sites:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
