networks:
  microservices-net:
    external: true

volumes:
  yacht_data:

services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "127.0.0.1:9007:8000"
    volumes:
      - yacht_data:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
