networks:
  microservices-net:
    external: true

services:
  element:
    container_name: element-web
    image: vectorim/element-web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:10240:80"
    networks:
      - microservices-net
    depends_on:
      - synapse
