networks:
  microservices-net:
    external: true

volumes:
  mattermost_data:
  mattermost_logs:
  mattermost_config:
  mattermost_plugins:

services:
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://postgres:admin1234567@postgres:5432/mattermost?sslmode=disable
      - MM_SERVICESETTINGS_SITEURL=http://localhost:10200
      - MM_SERVICESETTINGS_ENABLELOCALMODE=true
    ports:
      - "127.0.0.1:10200:8065"
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_config:/mattermost/config
      - mattermost_plugins:/mattermost/plugins
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8065/api/v4/system/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
