networks:
  microservices-net:
    external: true

volumes:
  zulip_data:

services:
  zulip:
    container_name: zulip
    image: zulip/docker-zulip:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - DB_HOST=postgres
      - DB_HOST_PORT=5432
      - DB_USER=postgres
      - POSTGRES_PASSWORD=admin1234567
      - SECRETS_postgres_password=admin1234567
      - ZULIP_AUTH_BACKENDS=EmailAuthBackend
      - SETTING_EXTERNAL_HOST=localhost:10230
      - SETTING_ZULIP_ADMINISTRATOR=admin@localhost
      - SETTING_EMAIL_HOST=
      - SETTING_EMAIL_HOST_USER=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "127.0.0.1:10230:80"
      - "127.0.0.1:10231:443"
    volumes:
      - zulip_data:/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
