networks:
  microservices-net:
    external: true

volumes:
  roundcube_data:

services:
  roundcube:
    container_name: roundcube
    image: roundcube/roundcubemail:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=postgres
      - ROUNDCUBEMAIL_DB_HOST=postgres
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DB_USER=postgres
      - ROUNDCUBEMAIL_DB_PASSWORD=admin1234567
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.example.com
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.example.com
    ports:
      - "127.0.0.1:8126:80"
    volumes:
      - roundcube_data:/var/roundcube/config
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
