networks:
  microservices-net:
    external: true

volumes:
  gitea_data:

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:9210:3000"
      - "127.0.0.1:2222:22"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - microservices-net
