# compose/project/openproject-worker.yml
networks:
  microservices-net:
    external: true

volumes:
  openproject_data:
    external: true

services:
  openproject-worker:
    container_name: openproject-worker
    image: openproject/openproject:16-slim
    restart: unless-stopped
    env_file: ../../.env
    environment:
      # Basic Configuration
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_HOST__NAME=openproject.test

      # Database Configuration
      - DATABASE_URL=postgres://postgres:${SHARED_DB_PASSWORD}@postgres:5432/openproject?pool=20&encoding=unicode&reconnect=true

      # Cache Configuration
      - RAILS_CACHE_STORE=redis_cache_store
      - OPENPROJECT_CACHE__REDIS__URL=redis://redis:6379/2

      # SMTP Configuration
      - EMAIL_DELIVERY_METHOD=smtp
      - SMTP_ADDRESS=mailpit
      - SMTP_PORT=1025
      - SMTP_DOMAIN=${DOMAIN_SUFFIX}
      - SMTP_AUTHENTICATION=none
      - SMTP_ENABLE_STARTTLS_AUTO=false
      - OPENPROJECT_MAIL__FROM=noreply@${DOMAIN_SUFFIX}
    command: "./docker/prod/worker"
    volumes:
      - openproject_data:/var/openproject/assets
    networks:
      - microservices-net
    depends_on:
      - openproject-seeder
