services:
  php:
    image: php:8.3-apache
    ports:
    - 127.0.0.1:8100:80
    - 127.0.0.1:8080:8080
    working_dir: /var/www/html
    volumes:
    - php_data:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    healthcheck:
      test:
      - CMD
      - sh
      - -c
      - curl -f http://localhost:80/ || exit 0
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
    - microservices-net
    container_name: php
volumes:
  php_data: null
networks:
  microservices-net:
    external: true
