services:
  php:
    build:
      context: ../config/php
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8100:8000"
      - "127.0.0.1:8080:8080"
    working_dir: /var/www/html
    volumes:
      - ../../apps:/var/www/html
      - php_config_php_ini:/usr/local/etc/php/php.ini:ro
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      COMPOSER_MEMORY_LIMIT: "-1"
    depends_on:
      - mailpit
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - microservices-net
    x-devarch-config:
      Dockerfile: /devarch/build/Dockerfile
      php.ini: /usr/local/etc/php/php.ini
    container_name: php

volumes:
  php_config_php_ini: null

networks:
  microservices-net:
    external: true
