networks:
  microservices-net:
    external: true

volumes:
  keycloak_data:

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=admin1234567
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=9710
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
    command: start-dev
    ports:
      - "127.0.0.1:9710:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - microservices-net
    depends_on:
      - postgres
