networks:
  microservices-net:
    external: true

volumes:
  vault_data:
  vault_logs:

services:
  vault:
    container_name: vault
    image: hashicorp/vault:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_ROOT_TOKEN:-root}
    ports:
      - "127.0.0.1:9700:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
    command: server -dev -dev-listen-address="0.0.0.0:8200"
    networks:
      - microservices-net
