networks:
  microservices-net:
    external: true

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8005:80"
      - "127.0.0.1:8006:443"
      - "127.0.0.1:8007:443/udp"
      - "127.0.0.1:2019:2019"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ../../config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/"]
      interval: 30s
      timeout: 10s
      retries: 3
