services:
  beekeeper-studio:
    image: beekeeperstudio/beekeeper-studio:5
    restart: unless-stopped
    ports:
    - 127.0.0.1:8608:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
    - microservices-net
    container_name: beekeeper-studio
networks:
  microservices-net:
    external: true
