services:
  drawdb:
    image: xinsodev/drawdb:1.0
    restart: unless-stopped
    ports:
    - 127.0.0.1:8089:80
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:80/
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
    - microservices-net
    container_name: drawdb
networks:
  microservices-net:
    external: true
