networks:
  microservices-net:
    external: true

volumes:
  docker_registry_data:

services:
  docker-registry:
    container_name: docker-registry
    image: registry:2
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    ports:
      - "127.0.0.1:9830:5000"
    volumes:
      - docker_registry_data:/var/lib/registry
    networks:
      - microservices-net
