networks:
  microservices-net:
    external: true

volumes:
  harbor_data:

services:
  harbor-core:
    container_name: harbor-core
    image: goharbor/harbor-core:v2.11.0
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - CORE_SECRET=${HARBOR_CORE_SECRET:-secret123}
      - JOBSERVICE_SECRET=${HARBOR_JOBSERVICE_SECRET:-secret123}
      - EXT_ENDPOINT=http://localhost:9800
      - DATABASE_TYPE=postgresql
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=admin1234567
      - POSTGRESQL_DATABASE=harbor
      - POSTGRESQL_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REGISTRY_URL=http://harbor-registry:5000
      - TOKEN_SERVICE_URL=http://harbor-core:8080/service/token
      - HARBOR_ADMIN_PASSWORD=${HARBOR_ADMIN_PASSWORD:-Harbor12345}
    ports:
      - "127.0.0.1:9800:8080"
    volumes:
      - harbor_data:/data
    networks:
      - microservices-net
    depends_on:
      - postgres
      - redis
      - harbor-registry
