networks:
  microservices-net:
    external: true

volumes:
  nexus_data:

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx2048m -XX:MaxDirectMemorySize=2048m
    ports:
      - "127.0.0.1:9810:8081"
      - "127.0.0.1:9811:8082"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - microservices-net
