networks:
  microservices-net:
    external: true

volumes:
  verdaccio_storage:
  verdaccio_plugins:

services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PUBLIC_URL=http://localhost:9820
    ports:
      - "127.0.0.1:9820:4873"
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_plugins:/verdaccio/plugins
    networks:
      - microservices-net
