networks:
  microservices-net:
    external: true

services:
  devarch-api:
    container_name: devarch-api
    build:
      context: ../../api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:admin1234567@postgres:5432/devarch?sslmode=disable
      - PORT=8080
      - DEVARCH_USE_SUDO=false
      - CONTAINER_HOST=unix:///run/podman/podman.sock
    ports:
      - "127.0.0.1:8550:8080"
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock:ro
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
