/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksIndexRouteImport } from './routes/stacks/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as RegistriesIndexRouteImport } from './routes/registries/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as NetworksIndexRouteImport } from './routes/networks/index'
import { Route as ImagesIndexRouteImport } from './routes/images/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as StacksNameRouteImport } from './routes/stacks/$name'
import { Route as ServicesNewRouteImport } from './routes/services/new'
import { Route as ServicesNameRouteImport } from './routes/services/$name'
import { Route as ProjectsNameRouteImport } from './routes/projects/$name'
import { Route as RegistriesRegistrySplatRouteImport } from './routes/registries/$registry.$'
import { Route as StacksNameInstancesInstanceRouteImport } from './routes/stacks/$name.instances.$instance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesIndexRoute = RegistriesIndexRouteImport.update({
  id: '/registries/',
  path: '/registries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksIndexRoute = NetworksIndexRouteImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksNameRoute = StacksNameRouteImport.update({
  id: '/stacks/$name',
  path: '/stacks/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNewRoute = ServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNameRoute = ServicesNameRouteImport.update({
  id: '/services/$name',
  path: '/services/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNameRoute = ProjectsNameRouteImport.update({
  id: '/projects/$name',
  path: '/projects/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesRegistrySplatRoute = RegistriesRegistrySplatRouteImport.update({
  id: '/registries/$registry/$',
  path: '/registries/$registry/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksNameInstancesInstanceRoute =
  StacksNameInstancesInstanceRouteImport.update({
    id: '/instances/$instance',
    path: '/instances/$instance',
    getParentRoute: () => StacksNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/services/$name': typeof ServicesNameRoute
  '/services/new': typeof ServicesNewRoute
  '/stacks/$name': typeof StacksNameRouteWithChildren
  '/categories/': typeof CategoriesIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/networks/': typeof NetworksIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/registries/': typeof RegistriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/registries/$registry/$': typeof RegistriesRegistrySplatRoute
  '/stacks/$name/instances/$instance': typeof StacksNameInstancesInstanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/services/$name': typeof ServicesNameRoute
  '/services/new': typeof ServicesNewRoute
  '/stacks/$name': typeof StacksNameRouteWithChildren
  '/categories': typeof CategoriesIndexRoute
  '/images': typeof ImagesIndexRoute
  '/networks': typeof NetworksIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/registries': typeof RegistriesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stacks': typeof StacksIndexRoute
  '/registries/$registry/$': typeof RegistriesRegistrySplatRoute
  '/stacks/$name/instances/$instance': typeof StacksNameInstancesInstanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/services/$name': typeof ServicesNameRoute
  '/services/new': typeof ServicesNewRoute
  '/stacks/$name': typeof StacksNameRouteWithChildren
  '/categories/': typeof CategoriesIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/networks/': typeof NetworksIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/registries/': typeof RegistriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/registries/$registry/$': typeof RegistriesRegistrySplatRoute
  '/stacks/$name/instances/$instance': typeof StacksNameInstancesInstanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/$name'
    | '/services/$name'
    | '/services/new'
    | '/stacks/$name'
    | '/categories/'
    | '/images/'
    | '/networks/'
    | '/projects/'
    | '/registries/'
    | '/services/'
    | '/settings/'
    | '/stacks/'
    | '/registries/$registry/$'
    | '/stacks/$name/instances/$instance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects/$name'
    | '/services/$name'
    | '/services/new'
    | '/stacks/$name'
    | '/categories'
    | '/images'
    | '/networks'
    | '/projects'
    | '/registries'
    | '/services'
    | '/settings'
    | '/stacks'
    | '/registries/$registry/$'
    | '/stacks/$name/instances/$instance'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects/$name'
    | '/services/$name'
    | '/services/new'
    | '/stacks/$name'
    | '/categories/'
    | '/images/'
    | '/networks/'
    | '/projects/'
    | '/registries/'
    | '/services/'
    | '/settings/'
    | '/stacks/'
    | '/registries/$registry/$'
    | '/stacks/$name/instances/$instance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsNameRoute: typeof ProjectsNameRoute
  ServicesNameRoute: typeof ServicesNameRoute
  ServicesNewRoute: typeof ServicesNewRoute
  StacksNameRoute: typeof StacksNameRouteWithChildren
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  NetworksIndexRoute: typeof NetworksIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RegistriesIndexRoute: typeof RegistriesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StacksIndexRoute: typeof StacksIndexRoute
  RegistriesRegistrySplatRoute: typeof RegistriesRegistrySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries/': {
      id: '/registries/'
      path: '/registries'
      fullPath: '/registries/'
      preLoaderRoute: typeof RegistriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks/': {
      id: '/networks/'
      path: '/networks'
      fullPath: '/networks/'
      preLoaderRoute: typeof NetworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$name': {
      id: '/stacks/$name'
      path: '/stacks/$name'
      fullPath: '/stacks/$name'
      preLoaderRoute: typeof StacksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/new': {
      id: '/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ServicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$name': {
      id: '/services/$name'
      path: '/services/$name'
      fullPath: '/services/$name'
      preLoaderRoute: typeof ServicesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$name': {
      id: '/projects/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries/$registry/$': {
      id: '/registries/$registry/$'
      path: '/registries/$registry/$'
      fullPath: '/registries/$registry/$'
      preLoaderRoute: typeof RegistriesRegistrySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$name/instances/$instance': {
      id: '/stacks/$name/instances/$instance'
      path: '/instances/$instance'
      fullPath: '/stacks/$name/instances/$instance'
      preLoaderRoute: typeof StacksNameInstancesInstanceRouteImport
      parentRoute: typeof StacksNameRoute
    }
  }
}

interface StacksNameRouteChildren {
  StacksNameInstancesInstanceRoute: typeof StacksNameInstancesInstanceRoute
}

const StacksNameRouteChildren: StacksNameRouteChildren = {
  StacksNameInstancesInstanceRoute: StacksNameInstancesInstanceRoute,
}

const StacksNameRouteWithChildren = StacksNameRoute._addFileChildren(
  StacksNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsNameRoute: ProjectsNameRoute,
  ServicesNameRoute: ServicesNameRoute,
  ServicesNewRoute: ServicesNewRoute,
  StacksNameRoute: StacksNameRouteWithChildren,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  NetworksIndexRoute: NetworksIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RegistriesIndexRoute: RegistriesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StacksIndexRoute: StacksIndexRoute,
  RegistriesRegistrySplatRoute: RegistriesRegistrySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
