services:
  erpnext-configurator:
    image: frappe/erpnext:v15
    restart: 'no'
    command: |
      bash -c "bench set-config -g db_host mariadb; bench set-config -gp db_port 3306; bench set-config -g redis_cache redis://redis:6379/0; bench set-config -g redis_queue redis://redis:6379/1; bench set-config -g redis_socketio redis://redis:6379/2"
    networks:
    - microservices-net
    container_name: erpnext-configurator
networks:
  microservices-net:
    external: true
