networks:
  microservices-net:
    external: true

volumes:
  npm_data:
  npm_letsencrypt:

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    build:
      context: ../../config/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ../../apps:/var/www/html
      - ../../config/nginx/custom:/data/nginx/custom
      - /etc/localtime:/etc/localtime:ro
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-proxy-manager.rule=Host(`${NGINX_DOMAIN}`)"
      - "traefik.http.routers.nginx-proxy-manager.tls=true"
      - "traefik.http.services.nginx-proxy-manager.loadbalancer.server.port=81"