networks:
  microservices-net:
    external: true

volumes:
  npm_data:
  npm_letsencrypt:

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    build:
      context: ../../config/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Dashboard
    volumes:
      - ../../apps:/var/www/html
      - ../../config/nginx/custom:/data/nginx/custom
      - /etc/localtime:/etc/localtime:ro
      - ../../config/traefik/certs/local.crt:/etc/letsencrypt/live/mkcert.test/local.crt
      - ../../config/traefik/certs/local.key:/etc/letsencrypt/live/mkcert.test/local.key
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-proxy-manager.rule=Host(`nginx.test`)"
      - "traefik.http.routers.nginx-proxy-manager.entrypoints=websecure"
      - "traefik.http.routers.nginx-proxy-manager.tls=true"
      - "traefik.http.services.nginx-proxy-manager.loadbalancer.server.port=81"
