networks:
  microservices-net:
    external: true

volumes:
  chromadb_data:

services:
  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - "127.0.0.1:8901:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
