networks:
  microservices-net:
    external: true

volumes:
  langflow_data:

services:
  langflow:
    container_name: langflow
    image: langflowai/langflow:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:////data/langflow.db
      - LANGFLOW_CONFIG_DIR=/data
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
    ports:
      - "127.0.0.1:7860:7860"
    volumes:
      - langflow_data:/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
