networks:
  microservices-net:
    external: true

volumes:
  langflow_data:

services:
  langflow:
    container_name: langflow
    image: langflowai/langflow:latest
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - langflow_data:/app/data
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langflow.rule=Host(`${LANGFLOW_DOMAIN}`)"
      - "traefik.http.routers.langflow.tls=true"
      - "traefik.http.services.langflow.loadbalancer.server.port=7860"