version: "3.8"

networks:
  microservices-net:
    external: true

volumes:
  n8n_data:

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "127.0.0.1:9100:5678"  # Local access to n8n
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - microservices-net