networks:
  microservices-net:
    external: true

volumes:
  n8n_data:

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_DOMAIN}`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"