networks:
  microservices-net:
    external: true

volumes:
  open_webui_data:

services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
      - WEBUI_NAME=DevArch AI
    ports:
      - "127.0.0.1:3080:8080"
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
