version: "3.8"

networks:
  microservices-net:
    external: true

volumes:
  keycloak_data:

services:
  keycloak:
    container_name: keycloak
    build:
      context: ../config/keycloak
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "127.0.0.1:9400:8443"  # Local access to Keycloak HTTPS
      - "127.0.0.1:9401:9000"  # Local access to Keycloak health/metrics
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - microservices-net