networks:
  microservices-net:
    external: true

volumes:
  pulsar_data:

services:
  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:latest
    restart: unless-stopped
    env_file: ../../.env
    command: bin/pulsar standalone
    ports:
      - "127.0.0.1:6650:6650"
      - "127.0.0.1:8281:8080"
    volumes:
      - pulsar_data:/pulsar/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
