networks:
  microservices-net:
    external: true

services:
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:10100:4444"
    networks:
      - microservices-net
