networks:
  microservices-net:
    external: true

volumes:
  k6_scripts:

services:
  k6:
    container_name: k6
    image: grafana/k6:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    ports:
      - "127.0.0.1:10110:6565"
    volumes:
      - k6_scripts:/scripts
    networks:
      - microservices-net
    command: run --vus 10 --duration 30s /scripts/test.js
