networks:
  microservices-net:
    external: true

services:
  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/node-firefox:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb
    networks:
      - microservices-net
