networks:
  microservices-net:
    external: true

volumes:
  nats_data:

services:
  nats:
    container_name: nats
    image: nats:latest
    restart: unless-stopped
    env_file: ../../.env
    command: "--store_dir /data --http_port 8222 --js"
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"
      - "127.0.0.1:6222:6222"
    volumes:
      - nats_data:/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
