networks:
  microservices-net:
    external: true

volumes:
  authentik_media:
  authentik_certs:
  authentik_templates:

services:
  authentik-worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:-change-me-please-use-random-string}
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__USER=postgres
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=admin1234567
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_ERROR_REPORTING__ENABLED=false
      - AUTHENTIK_LOG_LEVEL=${AUTHENTIK_LOG_LEVEL:-info}
    command: worker
    volumes:
      - authentik_media:/media
      - authentik_certs:/certs
      - authentik_templates:/templates
    networks:
      - microservices-net
    depends_on:
      - postgres
      - redis
