networks:
  microservices-net:
    external: true

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    env_file: ../../.env
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - "127.0.0.1:8082:8080"
    networks:
      - microservices-net