networks:
  microservices-net:
    external: true

volumes:
  metabase_data:

services:
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    env_file: ../../.env
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_HOST=postgres
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_PASS=${SHARED_DB_PASSWORD}
    ports:
      - "127.0.0.1:8085:3000"
    volumes:
      - metabase_data:/metabase-data
    networks:
      - microservices-net