# DevArch Typesense Server Configuration

[server]
api-address = 0.0.0.0
api-port = 8108
peering-address = 0.0.0.0
peering-port = 8107

[directories]
data-dir = /data
log-dir = /var/log/typesense

[tuning]
thread-pool-size = 4
num-memory-shards = 4

[security]
enable-cors = true
cors-domains = *

[logging]
log-level = info
