networks:
  microservices-net:
    external: true

volumes:
  zammad_data:
  zammad_postgres:
  zammad_elasticsearch:

services:
  zammad:
    container_name: zammad
    image: zammad/zammad-docker-compose:6.2.0-7
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - POSTGRES_HOST=zammad-db
      - POSTGRES_USER=zammad
      - POSTGRES_PASS=${ZAMMAD_DB_PASSWORD:-zammad123}
      - POSTGRES_DB=zammad
      - ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_HOST=zammad-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_URL=redis://redis:6379
    ports:
      - "127.0.0.1:9850:3000"
    volumes:
      - zammad_data:/opt/zammad
    networks:
      - microservices-net
    depends_on:
      - zammad-db
      - zammad-elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  zammad-db:
    container_name: zammad-db
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zammad
      - POSTGRES_PASSWORD=${ZAMMAD_DB_PASSWORD:-zammad123}
      - POSTGRES_DB=zammad
    volumes:
      - zammad_postgres:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zammad"]
      interval: 10s
      timeout: 5s
      retries: 5

  zammad-elasticsearch:
    container_name: zammad-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - zammad_elasticsearch:/usr/share/elasticsearch/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
