networks:
  microservices-net:
    external: true

volumes:
  deno_apps:

services:
  deno:
    container_name: deno
    image: denoland/deno:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - DENO_DIR=/deno-dir
    ports:
      - "127.0.0.1:4030:8000"
      - "127.0.0.1:4031:8001"
      - "127.0.0.1:4032:9229"  # Debug port
    volumes:
      - deno_apps:/app
      - ../../apps:/apps
    working_dir: /app
    command: deno run --allow-net --allow-read --watch server.ts
    networks:
      - microservices-net
