networks:
  microservices-net:
    external: true

services:
  dotnet:
    container_name: dotnet
    build:
      context: ../../config/dotnet
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8010:80" # HTTP
      - "127.0.0.1:8011:443" # HTTPS
    volumes:
      - ../../apps:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dotnet.rule=Host(`dotnet.test`)"
      - "traefik.http.routers.dotnet.entrypoints=websecure"
      - "traefik.http.routers.dotnet.tls=true"
      - "traefik.http.services.dotnet.loadbalancer.server.port=80"
