networks:
  microservices-net:
    external: true

services:
  dotnet:
    container_name: dotnet
    build:
      context: ../../config/dotnet
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ../../apps:/app
      - ../../logs/dotnet:/var/log/dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dotnet.rule=Host(`${DOTNET_DOMAIN}`)"
      - "traefik.http.routers.dotnet.tls=true"
      - "traefik.http.services.dotnet.loadbalancer.server.port=80"