networks:
  microservices-net:
    external: true

services:
  go:
    container_name: go
    build:
      context: ../../config/go
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ../../apps:/app
      - ../../logs/go:/var/log/go
    working_dir: /app
    command: ["go", "run", "main.go"]
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go.rule=Host(`${GO_DOMAIN}`)"
      - "traefik.http.routers.go.tls=true"
      - "traefik.http.services.go.loadbalancer.server.port=8080"