networks:
  microservices-net:
    external: true

services:
  go:
    container_name: go
    build:
      context: ../../config/go
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8020:8080" # Go application port
    volumes:
      - ../../apps:/app
    working_dir: /app
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go.rule=Host(`go.test`)"
      - "traefik.http.routers.go.entrypoints=websecure"
      - "traefik.http.routers.go.tls=true"
      - "traefik.http.services.go.loadbalancer.server.port=8080"
