networks:
  microservices-net:
    external: true

services:
  node:
    container_name: node
    build:
      context: ../../config/node
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ../../apps:/app
      - ../../logs/node:/var/log/node
    working_dir: /app
    command: ["npm", "start"]
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`${NODE_DOMAIN}`)"
      - "traefik.http.routers.node.tls=true"
      - "traefik.http.services.node.loadbalancer.server.port=3000"