version: "3.8"

networks:
  microservices-net:
    external: true

services:
  php:
    container_name: php
    build:
      context: ../config/php
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ../apps:/var/www/html
      - ../scripts:/var/www/scripts
      - ../../.env:/var/www/.env
      - ../config/php/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - microservices-net
