networks:
  microservices-net:
    external: true

services:
  python:
    container_name: python
    build:
      context: ../../config/python
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ../../apps:/app
      - ../../logs/python:/var/log/python
    working_dir: /app
    command: ["python", "main.py"]
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python.rule=Host(`${PYTHON_DOMAIN}`)"
      - "traefik.http.routers.python.tls=true"
      - "traefik.http.services.python.loadbalancer.server.port=8000"