version: "3.8"

networks:
  microservices-net:
    external: true

services:
  python:
    container_name: python
    build:
      context: ../../config/python
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8040:8000" # Python application port (FastAPI/Django)
    volumes:
      - ../../apps:/app
      - ../../logs/python:/var/log/python
    working_dir: /app
    command: ["python", "main.py"]
    networks:
      - microservices-net
