networks:
  microservices-net:
    external: true

services:
  python:
    container_name: python
    build:
      context: ../../config/python
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8040:8000" # Python application port (FastAPI/Django)
    volumes:
      - ../../apps:/app
      - ../../logs/python:/var/log/python
    working_dir: /app
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python.rule=Host(`python.test`)"
      - "traefik.http.routers.python.entrypoints=web"
      # - "traefik.http.routers.python.tls=false"
      - "traefik.http.services.python.loadbalancer.server.port=8000"
