networks:
  microservices-net:
    external: true

services:
  vite:
    container_name: vite
    build:
      context: ../../config/vite
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:5173:5173"  # Vite dev server 1
      - "127.0.0.1:5174:5174"  # Vite dev server 2
      - "127.0.0.1:5175:5175"  # Vite dev server 3
      - "127.0.0.1:5176:5176"  # Vite dev server 4
      - "127.0.0.1:5177:5177"  # Vite dev server 5
      - "127.0.0.1:5178:5178"  # Vite dev server 6
      - "127.0.0.1:5179:5179"  # Vite dev server 7
      - "127.0.0.1:5180:5180"  # Vite dev server 8
      - "127.0.0.1:5181:5181"  # Vite dev server 9
      - "127.0.0.1:5182:5182"  # Vite dev server 10
    volumes:
      - ../../apps:/apps
      - ../../scripts:/scripts:ro
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD", "node", "--version" ]
      interval: 30s
      timeout: 10s
      retries: 3
