services:
  kong:
    image: kong:3.9
    restart: unless-stopped
    ports:
    - 127.0.0.1:4002:8000
    - 127.0.0.1:4004:8001
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
    healthcheck:
      test:
      - CMD
      - kong
      - health
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
    - microservices-net
    container_name: kong
networks:
  microservices-net:
    external: true
