services:
  krakend:
    image: devopsfaith/krakend:2.7
    restart: unless-stopped
    ports:
    - 127.0.0.1:4000:8080
    healthcheck:
      test:
      - CMD-SHELL
      - wget --spider -q http://localhost:8080/__health
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
    - microservices-net
    x-devarch-config:
      krakend.json: /etc/krakend/krakend.json
    container_name: krakend
networks:
  microservices-net:
    external: true
