services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
    - 127.0.0.1:5672:5672
    - 127.0.0.1:15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: devarch
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test:
      - CMD
      - rabbitmq-diagnostics
      - -q
      - ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
    - microservices-net
    x-devarch-config:
      rabbitmq.conf: /etc/rabbitmq/rabbitmq.conf
      enabled_plugins: /etc/rabbitmq/enabled_plugins
    container_name: rabbitmq
volumes:
  rabbitmq_data: null
networks:
  microservices-net:
    external: true
