services:
  authelia:
    image: authelia/authelia:4.39
    restart: unless-stopped
    ports:
    - 127.0.0.1:9730:9091
    volumes:
    - authelia_data:/config
    healthcheck:
      test:
      - CMD-SHELL
      - wget --spider -q http://localhost:9091/api/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
    - microservices-net
    container_name: authelia
volumes:
  authelia_data: null
networks:
  microservices-net:
    external: true
