services:
  trivy:
    image: aquasec/trivy:0.58
    restart: unless-stopped
    command: server --listen 0.0.0.0:8080
    ports:
    - 127.0.0.1:9740:8080
    volumes:
    - trivy_data:/root/.cache
    healthcheck:
      test:
      - CMD-SHELL
      - wget --spider -q http://localhost:8080/healthz
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
    - microservices-net
    container_name: trivy
volumes:
  trivy_data: null
networks:
  microservices-net:
    external: true
