networks:
  microservices-net:
    external: true

volumes:
  grafana_data:

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0"
    env_file: ../../.env
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:9001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - microservices-net