networks:
  microservices-net:
    external: true

volumes:
  loki_data:

services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - loki_data:/loki
      - ../../config/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
