networks:
  microservices-net:
    external: true

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    command:
      - --config=/etc/otelcol-contrib/config.yaml
    volumes:
      - ../../config/otel-collector/otel-collector.yml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
      - "127.0.0.1:8889:8889"
      - "127.0.0.1:13133:13133"
      - "127.0.0.1:1777:1777"
    networks:
      - microservices-net