networks:
  microservices-net:
    external: true

volumes:
  tempo_data:

services:
  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:3200:3200"   # tempo
      - "127.0.0.1:9095:9095"   # tempo grpc
      - "127.0.0.1:14269:14268" # jaeger ingest
      - "127.0.0.1:4319:4317"   # otlp grpc
      - "127.0.0.1:4320:4318"   # otlp http
    volumes:
      - tempo_data:/tmp/tempo
      - ../../config/tempo/tempo-config.yml:/etc/tempo.yaml:ro
    command: -config.file=/etc/tempo.yaml
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3200/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
