networks:
  microservices-net:
    external: true

volumes:
  zipkin_data:

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "127.0.0.1:9412:9411"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3
