services:
  n8n:
    image: n8nio/n8n:1.72
    restart: unless-stopped
    ports:
    - 127.0.0.1:9910:5678
    environment:
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: devarch
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: '5432'
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: devarch
    volumes:
    - n8n_data:/home/node/.n8n
    healthcheck:
      test:
      - CMD-SHELL
      - wget --spider -q http://localhost:5678/healthz
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
    - microservices-net
    container_name: n8n
volumes:
  n8n_data: null
networks:
  microservices-net:
    external: true
