networks:
  microservices-net:
    external: true

volumes:
  azurite_data:

services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    env_file: ../../.env
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --debug /data/debug.log
    ports:
      - "127.0.0.1:9540:10000"
      - "127.0.0.1:9541:10001"
      - "127.0.0.1:9542:10002"
    volumes:
      - azurite_data:/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 30s
      timeout: 10s
      retries: 3
