networks:
  microservices-net:
    external: true

volumes:
  meilisearch_data:

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY:-masterKey123456789}
      - MEILI_ENV=development
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_LOG_LEVEL=INFO
      - MEILI_DB_PATH=/meili_data
      - MEILI_DUMP_DIR=/dumps
      - MEILI_SNAPSHOT_DIR=/snapshots
      - MEILI_MAX_INDEXING_MEMORY=256Mb
      - MEILI_MAX_INDEXING_THREADS=4
      - MEILI_PAYLOAD_SIZE_LIMIT=100Mb
    ports:
      - "127.0.0.1:7700:7700"
    volumes:
      - meilisearch_data:/meili_data
      - ../../config/meilisearch:/config:ro
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
