networks:
  microservices-net:
    external: true

volumes:
  solr_data:

services:
  solr:
    container_name: solr
    image: solr:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - SOLR_HEAP=512m
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - solr_data:/var/solr
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
