networks:
  microservices-net:
    external: true

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    env_file: ../../.env
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN}`)"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"