networks:
  microservices-net:
    external: true

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    env_file: ../../.env
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`${MONGODB_DOMAIN}`)"
      - "traefik.http.routers.mongo-express.tls=true"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"