version: "3.8"

networks:
  microservices-net:
    external: true

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    env_file: ../.env
    ports:
      - "127.0.0.1:8084:8081"  # Local access to Mongo Express
    networks:
      - microservices-net