networks:
  microservices-net:
    external: true

volumes:
  nocodb_data:

services:
  nocodb:
    container_name: nocodb
    image: nocodb/nocodb:latest
    restart: unless-stopped
    environment:
      - NC_DB=pg://${NC_DB_HOST}:${NC_DB_PORT}?u=${NC_DB_USER}&p=${NC_DB_PASSWORD}&d=${NC_DB_NAME}
      - NC_ADMIN_EMAIL=${NC_ADMIN_EMAIL}
      - NC_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}
      - NC_SERVER_HOST=0.0.0.0
      - NC_SERVER_PORT=8080
      - NC_DISABLE_TELE=true
      - NC_PUBLIC_URL=${NC_PUBLIC_URL}
      - NC_REDIS_URL=${NC_REDIS_URL}
      - NC_TOOL_DIR=/usr/app/data/
      - NC_ATTACHMENT_FIELD_SIZE=20971520
      - NC_SMTP_FROM=${NC_SMTP_FROM}
      - NC_SMTP_HOST=${NC_SMTP_HOST}
      - NC_SMTP_PORT=${NC_SMTP_PORT}
      - NC_SMTP_USERNAME=
      - NC_SMTP_PASSWORD=
      - NC_SMTP_SECURE=false
    ports:
      - "127.0.0.1:8086:8080"
    volumes:
      - nocodb_data:/usr/app/data
    networks:
      - microservices-net
