networks:
  microservices-net:
    external: true

volumes:
  pgadmin_data:

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_DOMAIN}`)"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"