version: "3.8"

networks:
  microservices-net:
    external: true

volumes:
  pgadmin_data:

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:8087:80" # Local access to pgAdmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - microservices-net
