networks:
  microservices-net:
    external: true

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    env_file: ../../.env
    ports:
      - "127.0.0.1:8083:80" # Local access to phpMyAdmin
    networks:
      - microservices-net
    volumes:
      - ../../config/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
