networks:
  microservices-net:
    external: true

services:
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-123456}
      - ADDRESS=0.0.0.0
      - PORT=8081
    ports:
      - "127.0.0.1:8088:8081" # Local access to Redis Commander
    networks:
      - microservices-net
