#!/bin/bash
# Auto-discovers Celery apps in Django projects and generates supervisord config
# Part of DevArch Multi-App Django Architecture

set -e

APPS_DIR="/app"
OUTPUT_DIR="/etc/supervisor/conf.d"
OUTPUT_FILE="$OUTPUT_DIR/auto-discovered-celery.conf"

echo "🌱 Celery Worker Auto-Discovery - DevArch"
echo "========================================"
echo "🔍 Scanning $APPS_DIR for Celery applications..."
echo ""

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Create empty config file
cat > "$OUTPUT_FILE" << 'HEADER'
; Auto-generated by celery-auto-discover.sh
; This file is regenerated on container startup
; DO NOT EDIT MANUALLY - changes will be lost

HEADER

app_count=0
beat_configured=false

for app_dir in "$APPS_DIR"/*/; do
    app_name=$(basename "$app_dir")

    # Skip special directories
    if [[ "$app_name" == "node_modules" ]] || [[ "$app_name" == "logs" ]] || [[ "$app_name" == ".git" ]]; then
        continue
    fi

    # Check for Celery configuration
    has_celery=false
    celery_app_module=""

    # Look for celery.py (Django pattern)
    if [ -f "$app_dir/$app_name/celery.py" ]; then
        has_celery=true
        celery_app_module="$app_name.celery:app"
        echo "🌱 Found Celery app: $app_name"
        echo "   Location: $app_dir"
        echo "   Module: $celery_app_module"
    # Look for standalone celery.py
    elif [ -f "$app_dir/celery.py" ]; then
        has_celery=true
        celery_app_module="celery:app"
        echo "🌱 Found Celery app: $app_name"
        echo "   Location: $app_dir"
        echo "   Module: $celery_app_module (standalone)"
    # Look for tasks.py (simple pattern)
    elif [ -f "$app_dir/tasks.py" ]; then
        has_celery=true
        celery_app_module="tasks:app"
        echo "🌱 Found Celery tasks: $app_name"
        echo "   Location: $app_dir"
        echo "   Module: $celery_app_module"
    fi

    # Skip if no Celery found
    if [ "$has_celery" = false ]; then
        continue
    fi

    # Install dependencies if requirements.txt exists
    if [ -f "$app_dir/requirements.txt" ]; then
        echo "   📥 Installing dependencies..."
        pip install --quiet -r "$app_dir/requirements.txt" 2>&1 | grep -E '(Successfully|already|ERROR)' || true
    fi

    # Queue name based on app
    queue_name="${app_name}_default"

    echo "   Queue: $queue_name"
    echo ""

    # Generate supervisord worker config
    cat >> "$OUTPUT_FILE" << EOF

[program:celery-worker-$app_name]
command=celery -A $celery_app_module worker --loglevel=info --queues=$queue_name --concurrency=2
directory=$app_dir
autostart=true
autorestart=true
stdout_logfile=/app/logs/celery-worker-$app_name.log
stderr_logfile=/app/logs/celery-worker-$app_name-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=PYTHONUNBUFFERED="1",APP_NAME="$app_name",C_FORCE_ROOT="true"
user=python
priority=999
stopwaitsecs=30
stopsignal=TERM

EOF

    # Configure beat scheduler (only for first app found)
    if [ "$beat_configured" = false ]; then
        cat >> "$OUTPUT_FILE" << EOF

[program:celery-beat-$app_name]
command=celery -A $celery_app_module beat --loglevel=info
directory=$app_dir
autostart=true
autorestart=true
stdout_logfile=/app/logs/celery-beat-$app_name.log
stderr_logfile=/app/logs/celery-beat-$app_name-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=PYTHONUNBUFFERED="1",APP_NAME="$app_name",C_FORCE_ROOT="true"
user=python
priority=998
stopwaitsecs=10
stopsignal=TERM

EOF
        beat_configured=true
        echo "   ✅ Beat scheduler configured (primary)"
    fi

    ((app_count++))
done

echo "========================================"
if [ $app_count -eq 0 ]; then
    echo "⚠️  No Celery applications found"
    echo ""
    echo "💡 To add Celery to a Django app:"
    echo "   1. Install celery: pip install celery[redis]"
    echo "   2. Create $APPS_DIR/myapp/myapp/celery.py"
    echo "   3. Configure Celery app with Redis broker"
    echo "   4. Restart container: devarch restart celery"
    echo ""
    echo "✅ Supervisord config generated (empty)"
else
    echo "✅ Generated supervisord config for $app_count worker(s)"
    echo "📍 Config file: $OUTPUT_FILE"
    echo ""
    echo "💡 Access Flower monitoring UI:"
    echo "   http://localhost:8303"
    echo ""
fi
echo "========================================"
echo ""

# Start Flower monitoring if any apps found
if [ $app_count -gt 0 ]; then
    echo "🌺 Starting Flower monitoring..."
    # Find first celery app for Flower
    for app_dir in "$APPS_DIR"/*/; do
        app_name=$(basename "$app_dir")
        if [ -f "$app_dir/$app_name/celery.py" ]; then
            celery_app="$app_name.celery:app"
            echo "   Using app: $celery_app"
            cd "$app_dir"
            celery -A "$celery_app" flower --port=5555 --broker="${CELERY_BROKER_URL}" &
            break
        elif [ -f "$app_dir/celery.py" ]; then
            cd "$app_dir"
            celery -A celery:app flower --port=5555 --broker="${CELERY_BROKER_URL}" &
            break
        fi
    done
fi

echo "🚀 Starting supervisord..."
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
