#!/bin/bash
# Auto-discovers Python apps on container start and generates supervisord config
# Part of DevArch Multi-Language Backend Architecture

set -e

APPS_DIR="/app"
OUTPUT_DIR="/etc/supervisor/conf.d"
OUTPUT_FILE="$OUTPUT_DIR/auto-discovered-apps.conf"
BASE_PORT=8000

echo "🐍 Python Apps Auto-Discovery - DevArch"
echo "========================================"
echo "🔍 Scanning $APPS_DIR for Python applications..."
echo ""

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Create empty config file
cat > "$OUTPUT_FILE" << 'HEADER'
; Auto-generated by python-auto-discover.sh
; This file is regenerated on container startup
; DO NOT EDIT MANUALLY - changes will be lost

HEADER

port=$BASE_PORT
app_count=0

for app_dir in "$APPS_DIR"/*/; do
    app_name=$(basename "$app_dir")

    # Skip special directories
    if [[ "$app_name" == "node_modules" ]] || [[ "$app_name" == "logs" ]] || [[ "$app_name" == ".git" ]]; then
        continue
    fi

    # Skip non-Python apps
    has_requirements=false
    has_manage_py=false
    has_pyproject=false
    has_uv_lock=false

    if [ -f "$app_dir/requirements.txt" ]; then
        has_requirements=true
    fi

    if [ -f "$app_dir/manage.py" ]; then
        has_manage_py=true
    fi

    if [ -f "$app_dir/pyproject.toml" ]; then
        has_pyproject=true
    fi

    if [ -f "$app_dir/uv.lock" ]; then
        has_uv_lock=true
    fi

    # Must have at least one Python marker
    if [ "$has_requirements" = false ] && [ "$has_manage_py" = false ] && [ "$has_pyproject" = false ] && [ "$has_uv_lock" = false ]; then
        continue
    fi

    echo "📦 Found Python app: $app_name"
    echo "   Location: $app_dir"

    # Install dependencies (prefer UV if available)
    if [ "$has_uv_lock" = true ]; then
        echo "   📥 Installing dependencies with UV (from uv.lock)..."
        cd "$app_dir" && uv pip install --quiet -r requirements.txt 2>&1 | grep -E '(Successfully|already|ERROR|Resolved)' || true
    elif [ "$has_requirements" = true ]; then
        echo "   📥 Installing dependencies with pip (from requirements.txt)..."
        pip install --quiet -r "$app_dir/requirements.txt" 2>&1 | grep -E '(Successfully|already|ERROR)' || true
    fi

    # Detect framework and configure command
    framework="unknown"
    command=""

    if [ "$has_manage_py" = true ]; then
        # Django
        framework="Django"

        # Check for production WSGI config
        if [ -f "$app_dir/config/wsgi.py" ]; then
            command="gunicorn config.wsgi:application --bind 0.0.0.0:$port --reload --workers 2"
        elif [ -f "$app_dir/wsgi.py" ]; then
            command="gunicorn wsgi:application --bind 0.0.0.0:$port --reload --workers 2"
        else
            # Fallback to development server
            command="python manage.py runserver 0.0.0.0:$port"
        fi

    elif grep -q "Flask" "$app_dir/requirements.txt" 2>/dev/null; then
        # Flask
        framework="Flask"

        if [ -f "$app_dir/app.py" ]; then
            command="gunicorn app:app --bind 0.0.0.0:$port --reload --workers 2"
        elif [ -f "$app_dir/wsgi.py" ]; then
            command="gunicorn wsgi:app --bind 0.0.0.0:$port --reload --workers 2"
        else
            command="python -m flask run --host=0.0.0.0 --port=$port"
        fi

    elif grep -q "fastapi" "$app_dir/requirements.txt" 2>/dev/null; then
        # FastAPI
        framework="FastAPI"

        if [ -f "$app_dir/main.py" ]; then
            command="uvicorn main:app --host 0.0.0.0 --port $port --reload"
        elif [ -f "$app_dir/app.py" ]; then
            command="uvicorn app:app --host 0.0.0.0 --port $port --reload"
        else
            echo "   ⚠️  FastAPI app found but no main.py or app.py entry point"
            continue
        fi

    else
        echo "   ⚠️  Could not detect framework - skipping"
        continue
    fi

    echo "   Framework: $framework"
    echo "   Port: $port"
    echo "   Command: $command"
    echo ""

    # Generate supervisord program config
    cat >> "$OUTPUT_FILE" << EOF

[program:$app_name]
command=$command
directory=$app_dir
autostart=true
autorestart=true
stdout_logfile=/app/logs/$app_name.log
stderr_logfile=/app/logs/$app_name-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=PYTHONUNBUFFERED="1",PORT="$port",APP_NAME="$app_name"
user=python
priority=999
stopwaitsecs=10

EOF

    ((app_count++))
    ((port++))
done

echo "========================================"
if [ $app_count -eq 0 ]; then
    echo "⚠️  No Python applications found"
    echo ""
    echo "💡 To create a Python app:"
    echo "   1. Use PyCharm IDE: File → New Project → Django/Flask"
    echo "   2. Location: $APPS_DIR/my-python-app"
    echo "   3. Create requirements.txt with dependencies"
    echo "   4. Restart container: devarch restart python"
    echo ""
    echo "✅ Supervisord config generated (empty)"
else
    echo "✅ Generated supervisord config for $app_count app(s)"
    echo "📍 Config file: $OUTPUT_FILE"
    echo ""
    echo "📊 Port mapping:"
    for ((i=0; i<app_count; i++)); do
        external_port=$((8300 + i))
        internal_port=$((8000 + i))
        echo "   App $((i+1)): localhost:$external_port → :$internal_port"
    done
    echo ""
fi
echo "========================================"
echo ""
echo "🚀 Starting supervisord..."
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
