#!/bin/bash
# Auto-discovers Vite configs in Django apps and generates supervisord config
# Part of DevArch Multi-App Django Architecture

set -e

APPS_DIR="/apps"
OUTPUT_DIR="/etc/supervisor/conf.d"
OUTPUT_FILE="$OUTPUT_DIR/auto-discovered-vite.conf"
BASE_PORT=5173

echo "⚡ Vite Dev Server Auto-Discovery - DevArch"
echo "========================================"
echo "🔍 Scanning $APPS_DIR for Vite configurations..."
echo ""

# Ensure output directory exists
sudo mkdir -p "$OUTPUT_DIR"

# Create empty config file
sudo cat > "$OUTPUT_FILE" << 'HEADER'
; Auto-generated by vite-auto-discover.sh
; This file is regenerated on container startup
; DO NOT EDIT MANUALLY - changes will be lost

HEADER

port=$BASE_PORT
app_count=0

for app_dir in "$APPS_DIR"/*/; do
    app_name=$(basename "$app_dir")

    # Skip special directories
    if [[ "$app_name" == "node_modules" ]] || [[ "$app_name" == "logs" ]] || [[ "$app_name" == ".git" ]]; then
        continue
    fi

    # Check for vite.config.js or vite.config.ts
    has_vite_config=false
    vite_config_file=""

    if [ -f "$app_dir/vite.config.js" ]; then
        has_vite_config=true
        vite_config_file="vite.config.js"
    elif [ -f "$app_dir/vite.config.ts" ]; then
        has_vite_config=true
        vite_config_file="vite.config.ts"
    fi

    # Skip if no Vite config found
    if [ "$has_vite_config" = false ]; then
        continue
    fi

    echo "⚡ Found Vite app: $app_name"
    echo "   Location: $app_dir"
    echo "   Config: $vite_config_file"

    # Install node_modules if package.json exists
    if [ -f "$app_dir/package.json" ]; then
        echo "   📥 Installing npm dependencies..."
        cd "$app_dir" && npm install --quiet 2>&1 | grep -E '(added|up to date|ERROR)' || true
    fi

    echo "   Port: $port"
    echo ""

    # Generate supervisord program config
    sudo cat >> "$OUTPUT_FILE" << EOF

[program:vite-$app_name]
command=npx vite --host 0.0.0.0 --port $port
directory=$app_dir
autostart=true
autorestart=true
stdout_logfile=/apps/logs/vite-$app_name.log
stderr_logfile=/apps/logs/vite-$app_name-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=NODE_ENV="development",PORT="$port",APP_NAME="$app_name"
user=node
priority=999
stopwaitsecs=10

EOF

    ((app_count++))
    ((port++))
done

echo "========================================"
if [ $app_count -eq 0 ]; then
    echo "⚠️  No Vite configurations found"
    echo ""
    echo "💡 To add Vite to a Django app:"
    echo "   1. Install django-vite: pip install django-vite"
    echo "   2. Create vite.config.js in your app directory"
    echo "   3. Configure assets entry points"
    echo "   4. Restart container: devarch restart vite"
    echo ""
    echo "✅ Supervisord config generated (empty)"
else
    echo "✅ Generated supervisord config for $app_count app(s)"
    echo "📍 Config file: $OUTPUT_FILE"
    echo ""
    echo "📊 Port mapping:"
    for ((i=0; i<app_count; i++)); do
        external_port=$((5173 + i))
        echo "   Vite server $((i+1)): localhost:$external_port"
    done
    echo ""
    echo "💡 Access Vite dev server:"
    echo "   Add to Nginx config: /@vite/client → vite:517X"
    echo ""
fi
echo "========================================"
echo ""
echo "🚀 Starting supervisord..."
exec sudo /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
