networks:
  microservices-net:
    external: true

volumes:
  mailpit_data:

services:
  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    env_file: ../../.env
    volumes:
      - mailpit_data:/data
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`${MAILPIT_DOMAIN}`)"
      - "traefik.http.routers.mailpit.tls=true"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"