networks:
  microservices-net:
    external: true

volumes:
  mailpit_data:

services:
  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    env_file: ../../.env
    volumes:
      - mailpit_data:/data
    ports:
      - "127.0.0.1:9201:1025" # Local access to SMTP
      - "127.0.0.1:9200:8025" # Local access to web UI
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`mailpit.test`)"
      - "traefik.http.routers.mailpit.entrypoints=web"
      # - "traefik.http.routers.mailpit.tls=false"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
