networks:
  microservices-net:
    external: true

services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: unless-stopped
    env_file: ../../.env
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8125:8025"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/"]
      interval: 30s
      timeout: 10s
      retries: 3
