networks:
  microservices-net:
    external: true

volumes:
  postal_data:

services:
  postal:
    container_name: postal
    image: ghcr.io/postalserver/postal:latest
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - POSTAL_MYSQL_HOST=postal-mysql
      - POSTAL_MYSQL_DATABASE=postal
      - POSTAL_MYSQL_USERNAME=postal
      - POSTAL_MYSQL_PASSWORD=admin1234567
      - POSTAL_RABBITMQ_HOST=rabbitmq
      - POSTAL_RABBITMQ_USERNAME=guest
      - POSTAL_RABBITMQ_PASSWORD=guest
    ports:
      - "127.0.0.1:8127:5000"
    volumes:
      - postal_data:/opt/postal/config
    networks:
      - microservices-net
    depends_on:
      - postal-mysql
