networks:
  microservices-net:
    external: true

volumes:
  elasticsearch_data:

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`${ELASTICSEARCH_DOMAIN}`)"
      - "traefik.http.routers.elasticsearch.tls=true"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"