networks:
  microservices-net:
    external: true

volumes:
  grafana_data:

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0"
    env_file: ../../.env
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"