networks:
  microservices-net:
    external: true

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.2
    restart: unless-stopped
    env_file: ../../.env
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`${KIBANA_DOMAIN}`)"
      - "traefik.http.routers.kibana.tls=true"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"