networks:
  microservices-net:
    external: true

services:
  kong:
    image: kong:3.9.1
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ../../config/kong/kong.yml:/kong/declarative/kong.yml:ro
    ports:
      - "127.0.0.1:4002:8000"
      - "127.0.0.1:4004:8001"
    networks:
      - microservices-net
