networks:
  microservices-net:
    external: true

services:
  mongodb-exporter:
    container_name: mongodb-exporter
    image: bitnami/mongodb-exporter:latest
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - "127.0.0.1:9216:9216"
    networks:
      - microservices-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongodb-exporter.rule=Host(`mongodb-exporter.test`)"
      - "traefik.http.routers.mongodb-exporter.entrypoints=web"
      # - "traefik.http.routers.mongodb-exporter.tls=false"
      - "traefik.http.services.mongodb-exporter.loadbalancer.server.port=9216"