networks:
  microservices-net:
    external: true

services:
  mysqld-exporter:
    container_name: mysqld-exporter
    image: prom/mysqld-exporter:v0.15.1
    restart: unless-stopped
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${SHARED_DB_PASSWORD}
    command:
      - "--mysqld.address=mariadb:3306"
      - "--mysqld.username=root"
      - "--web.listen-address=:9104"
    ports:
      - "127.0.0.1:9104:9104"
    networks:
      - microservices-net
