#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC="$SCRIPT_DIR/sync-hosts.sh"
TEST_TMP="$(mktemp -d)"
PROJECT="$TEST_TMP/project"
HOSTS_FIXTURE="$TEST_TMP/hosts"
passed=0

cleanup() { rm -rf "$TEST_TMP"; }
trap cleanup EXIT
fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }
pass() { ((passed += 1)); }

mkdir -p \
  "$PROJECT/services-library/data/redis" \
  "$PROJECT/services-library/web/nginx" \
  "$PROJECT/apps/alpha/public" \
  "$PROJECT/apps/beta" \
  "$PROJECT/apps/not-routable" \
  "$PROJECT/apps/.devarch-backups/ignored"
cat > "$PROJECT/services-library/data/redis/compose.yml" <<'EOF'
services:
  redis:
    container_name: redis
EOF
cat > "$PROJECT/services-library/web/nginx/compose.yml" <<'EOF'
services:
  nginx:
    container_name: "nginx-proxy-manager"
  duplicate:
    container_name: redis # duplicate is intentional
EOF
: > "$PROJECT/apps/alpha/public/index.php"
: > "$PROJECT/apps/beta/package.json"
cat > "$HOSTS_FIXTURE" <<'EOF'
127.0.0.1 localhost
# unrelated comment
192.0.2.10 retained.test
EOF

DEVARCH_PROJECT_ROOT="$PROJECT" HOSTS_FILE="$HOSTS_FIXTURE" DEVARCH_HOSTS_PLATFORM=unix "$SYNC" >/dev/null
expected="$TEST_TMP/expected"
cat > "$expected" <<'EOF'
127.0.0.1 localhost
# unrelated comment
192.0.2.10 retained.test

# BEGIN DEVARCH HOSTS
# Generated by scripts/hosts/sync-hosts.sh; rerun to refresh.
# Infrastructure services
127.0.0.1 nginx-proxy-manager.test redis.test
# Development applications
127.0.0.1 alpha.test beta.test
# Development tools
127.0.0.1 devarch.test
# END DEVARCH HOSTS
EOF
cmp -s "$HOSTS_FIXTURE" "$expected" || fail 'initial synchronization did not create the expected managed block'
pass

before="$(cksum "$HOSTS_FIXTURE")"
DEVARCH_PROJECT_ROOT="$PROJECT" HOSTS_FILE="$HOSTS_FIXTURE" DEVARCH_HOSTS_PLATFORM=unix "$SYNC" >/dev/null
after="$(cksum "$HOSTS_FIXTURE")"
[[ "$before" == "$after" ]] || fail 're-running synchronization changed a current hosts file'
pass

sed -i 's/nginx-proxy-manager/nginx-edge/' "$PROJECT/services-library/web/nginx/compose.yml"
DEVARCH_PROJECT_ROOT="$PROJECT" HOSTS_FILE="$HOSTS_FIXTURE" DEVARCH_HOSTS_PLATFORM=unix "$SYNC" >/dev/null
grep -Fxq '127.0.0.1 nginx-edge.test redis.test' "$HOSTS_FIXTURE" || fail 'managed block was not refreshed'
! grep -q 'nginx-proxy-manager.test' "$HOSTS_FIXTURE" || fail 'stale managed domain was retained'
grep -Fxq '192.0.2.10 retained.test' "$HOSTS_FIXTURE" || fail 'content outside the managed block changed'
pass

before="$(cksum "$HOSTS_FIXTURE")"
dry_run="$(DEVARCH_PROJECT_ROOT="$PROJECT" HOSTS_FILE="$HOSTS_FIXTURE" DEVARCH_HOSTS_PLATFORM=unix "$SYNC" --dry-run)"
after="$(cksum "$HOSTS_FIXTURE")"
[[ "$before" == "$after" ]] || fail 'dry-run changed the hosts file'
grep -Fq '# BEGIN DEVARCH HOSTS' <<<"$dry_run" || fail 'dry-run did not print the managed block'
pass

mkdir -p "$PROJECT/services-library/bad/invalid"
printf 'services:\n  bad:\n    container_name: Bad_Name\n' > "$PROJECT/services-library/bad/invalid/compose.yml"
if DEVARCH_PROJECT_ROOT="$PROJECT" HOSTS_FILE="$HOSTS_FIXTURE" DEVARCH_HOSTS_PLATFORM=unix "$SYNC" >/dev/null 2>&1; then
  fail 'invalid container_name should fail synchronization'
fi
pass

printf '# BEGIN DEVARCH HOSTS\nunterminated\n' > "$HOSTS_FIXTURE"
rm -rf "$PROJECT/services-library/bad"
if DEVARCH_PROJECT_ROOT="$PROJECT" HOSTS_FILE="$HOSTS_FIXTURE" DEVARCH_HOSTS_PLATFORM=unix "$SYNC" >/dev/null 2>&1; then
  fail 'an unmatched managed-block marker should fail safely'
fi
grep -Fxq 'unterminated' "$HOSTS_FIXTURE" || fail 'malformed hosts fixture changed on failure'
pass

printf 'PASS: %d assertions\n' "$passed"
