#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${DEVARCH_PROJECT_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
ADDRESS="127.0.0.1"
DRY_RUN=false
BEGIN_MARKER="# BEGIN DEVARCH HOSTS"
END_MARKER="# END DEVARCH HOSTS"

usage() {
  cat <<'EOF'
Usage: scripts/hosts/sync-hosts.sh [options]

Discover DevArch service and application domains and synchronize a managed
block in the operating system hosts file.

Options:
  --address IP   Address to map (default: 127.0.0.1)
  --dry-run      Print the generated managed block without changing the hosts file
  -h, --help     Show this help
EOF
}

die() { printf '[hosts] error: %s\n' "$*" >&2; exit 1; }

while (($# > 0)); do
  case "$1" in
    --address)
      (($# >= 2)) || die '--address requires a value'
      ADDRESS="$2"
      shift 2
      ;;
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

[[ "$ADDRESS" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || die 'address must be an IPv4 address'
IFS=. read -r -a address_parts <<<"$ADDRESS"
for part in "${address_parts[@]}"; do
  ((10#$part <= 255)) || die 'address must be an IPv4 address'
done
[[ -d "$PROJECT_ROOT/services-library" ]] || die "services library not found: $PROJECT_ROOT/services-library"
[[ -d "$PROJECT_ROOT/apps" ]] || die "apps directory not found: $PROJECT_ROOT/apps"

service_names=()
while IFS= read -r compose_file; do
  while IFS= read -r name; do
    [[ -n "$name" ]] && service_names+=("$name")
  done < <(sed -nE "s/^[[:space:]]*container_name:[[:space:]]*['\"]?([^[:space:]'\"#]+).*/\1/p" "$compose_file")
done < <(find "$PROJECT_ROOT/services-library" -type f \( -name 'compose.yml' -o -name 'compose.yaml' \) -print | LC_ALL=C sort)

app_names=()
for app_dir in "$PROJECT_ROOT"/apps/*; do
  [[ -d "$app_dir" ]] || continue
  app_name="${app_dir##*/}"
  if [[ -f "$app_dir/index.php" || -f "$app_dir/public/index.php" || -f "$app_dir/public/index.html" || -f "$app_dir/package.json" ]]; then
    app_names+=("$app_name")
  fi
done

sorted_names=()
while IFS= read -r name; do sorted_names+=("$name"); done < <(printf '%s\n' "${service_names[@]}" | sed '/^$/d' | LC_ALL=C sort -u)
service_names=("${sorted_names[@]}")
sorted_names=()
while IFS= read -r name; do sorted_names+=("$name"); done < <(printf '%s\n' "${app_names[@]}" | sed '/^$/d' | LC_ALL=C sort -u)
app_names=("${sorted_names[@]}")
((${#service_names[@]} > 0)) || die 'no service container_name values were discovered'

validate_label() {
  local label="$1" source="$2"
  [[ "$label" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]] || die "invalid DNS label from $source: $label"
}
for name in "${service_names[@]}"; do validate_label "$name" 'container_name'; done
for name in "${app_names[@]}"; do validate_label "$name" 'apps directory'; done

block_file="$(mktemp)"
temp_file=""
cleanup() { rm -f "$block_file" ${temp_file:+"$temp_file"}; }
trap cleanup EXIT

write_domains() {
  local heading="$1"; shift
  local domains=("$@") index=0
  printf '# %s\n' "$heading"
  while ((index < ${#domains[@]})); do
    printf '%s' "$ADDRESS"
    for ((column = 0; column < 6 && index < ${#domains[@]}; column++, index++)); do
      printf ' %s.test' "${domains[$index]}"
    done
    printf '\n'
  done
}

{
  printf '%s\n' "$BEGIN_MARKER"
  printf '# Generated by scripts/hosts/sync-hosts.sh; rerun to refresh.\n'
  write_domains 'Infrastructure services' "${service_names[@]}"
  write_domains 'Development applications' "${app_names[@]}"
  printf '# Development tools\n%s devarch.test\n' "$ADDRESS"
  printf '%s\n' "$END_MARKER"
} > "$block_file"

if [[ "$DRY_RUN" == true ]]; then
  cat "$block_file"
  printf '[hosts] discovered %d service and %d application domains (%d total)\n' \
    "${#service_names[@]}" "${#app_names[@]}" "$(( ${#service_names[@]} + ${#app_names[@]} + 1 ))" >&2
  exit 0
fi

platform="${DEVARCH_HOSTS_PLATFORM:-}"
if [[ -z "$platform" ]]; then
  uname_value="$(uname -s)"
  case "$uname_value" in
    Darwin|Linux)
      if [[ "$uname_value" == Linux ]] && grep -qi microsoft /proc/sys/kernel/osrelease 2>/dev/null; then platform=windows; else platform=unix; fi
      ;;
    MINGW*|MSYS*|CYGWIN*) platform=windows ;;
    *) die "unsupported operating system: $uname_value" ;;
  esac
fi

if [[ "$platform" == windows ]]; then
  command -v powershell.exe >/dev/null 2>&1 || die 'powershell.exe is required to update the Windows hosts file'
  powershell_script="$SCRIPT_DIR/sync-hosts.ps1"
  if command -v wslpath >/dev/null 2>&1; then powershell_script="$(wslpath -w "$powershell_script")"
  elif command -v cygpath >/dev/null 2>&1; then powershell_script="$(cygpath -w "$powershell_script")"
  fi
  block_base64="$(base64 < "$block_file" | tr -d '\r\n')"
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$powershell_script" -BlockBase64 "$block_base64"
  exit $?
fi

[[ "$platform" == unix ]] || die "unsupported hosts platform override: $platform"
hosts_file="${HOSTS_FILE:-/etc/hosts}"
[[ -f "$hosts_file" ]] || die "hosts file not found: $hosts_file"
begin_count="$(grep -Fxc "$BEGIN_MARKER" "$hosts_file" || true)"
end_count="$(grep -Fxc "$END_MARKER" "$hosts_file" || true)"
[[ "$begin_count" == "$end_count" && "$begin_count" =~ ^[01]$ ]] || die 'hosts file contains malformed or duplicate DevArch managed-block markers'

temp_file="$(mktemp)"
if [[ "$begin_count" == 1 ]]; then
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v block="$block_file" '
    function insert_block( line) { while ((getline line < block) > 0) print line; close(block) }
    $0 == begin { insert_block(); managed = 1; next }
    managed && $0 == end { managed = 0; closed = 1; next }
    !managed { print }
    END { if (managed || !closed) exit 2 }
  ' "$hosts_file" > "$temp_file" || die 'failed to replace the DevArch managed block safely'
else
  cat "$hosts_file" > "$temp_file"
  if [[ -s "$hosts_file" ]]; then
    [[ "$(tail -c 1 "$hosts_file" | wc -l)" == 1 ]] || printf '\n' >> "$temp_file"
    printf '\n' >> "$temp_file"
  fi
  cat "$block_file" >> "$temp_file"
fi

if cmp -s "$hosts_file" "$temp_file"; then
  printf '[hosts] managed block already current in %s (%d domains)\n' "$hosts_file" "$(( ${#service_names[@]} + ${#app_names[@]} + 1 ))"
  exit 0
fi

if [[ -w "$hosts_file" ]]; then
  cat "$temp_file" > "$hosts_file"
elif command -v sudo >/dev/null 2>&1; then
  printf '[hosts] administrator access is required to update %s\n' "$hosts_file"
  cat "$temp_file" | sudo tee "$hosts_file" >/dev/null
else
  die "administrator access is required to update $hosts_file (sudo not found)"
fi
printf '[hosts] synchronized %d service and %d application domains in %s\n' \
  "${#service_names[@]}" "${#app_names[@]}" "$hosts_file"
