services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
    - 127.0.0.1:8005:80
    - 127.0.0.1:8006:443
    - 127.0.0.1:2019:2019
    volumes:
    - caddy_data:/data
    - caddy_config:/config
    healthcheck:
      test:
      - CMD-SHELL
      - wget --spider -q http://localhost:2019/config/ || caddy version
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
    - microservices-net
    x-devarch-config:
      Caddyfile: /etc/caddy/Caddyfile
    container_name: caddy
volumes:
  caddy_data: null
  caddy_config: null
networks:
  microservices-net:
    external: true
