// Package hosts manages DevArch's block in the operating-system hosts file.
//
// On Linux and macOS DevArch edits /etc/hosts itself (through sudo tee when the
// file is not writable). On WSL, MSYS and Cygwin the browser resolves names
// through the Windows hosts file, so DevArch hands the edit to the embedded
// PowerShell helpers, which preserve the file's encoding and request UAC
// elevation.
package hosts

import (
	"bytes"
	"context"
	"embed"
	"encoding/base64"
	"errors"
	"fmt"
	"net"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"

	"github.com/prospect-ogujiuba/devarch/cli/internal/catalog"
	"github.com/prospect-ogujiuba/devarch/cli/internal/runner"
)

const (
	BeginMarker = "# BEGIN DEVARCH HOSTS"
	EndMarker   = "# END DEVARCH HOSTS"
	// DefaultAddress is where every DevArch domain points.
	DefaultAddress = "127.0.0.1"
	perLine        = 6
)

var (
	labelRE    = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`)
	hostnameRE = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$`)
)

//go:embed windows/*.ps1
var windowsScripts embed.FS

// Domains is the discovered set of DevArch names, without the .test suffix.
type Domains struct {
	Services []string
	Apps     []string
}

// Count is the number of hostnames the block maps, including devarch.test.
func (d Domains) Count() int { return len(d.Services) + len(d.Apps) + 1 }

// Discover collects service labels (every container_name plus .test hosts in
// x-devarch urls) and routable apps/ directories. Invalid DNS labels are errors.
func Discover(cat *catalog.Catalog, appsDir string) (Domains, error) {
	services := map[string]bool{}
	for _, s := range cat.Services {
		for _, c := range s.Containers {
			if c.ContainerName == "" {
				continue
			}
			if !labelRE.MatchString(c.ContainerName) {
				return Domains{}, fmt.Errorf("invalid DNS label from container_name in %s: %s", s.ID, c.ContainerName)
			}
			services[c.ContainerName] = true
		}
		for _, raw := range s.Meta.URLs {
			if label, ok := TestLabel(raw); ok {
				services[label] = true
			}
		}
	}
	if len(services) == 0 {
		return Domains{}, errors.New("no service container_name values were discovered")
	}
	var apps []string
	entries, err := os.ReadDir(appsDir)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return Domains{}, err
	}
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") || !Routable(filepath.Join(appsDir, e.Name())) {
			continue
		}
		if !labelRE.MatchString(e.Name()) {
			return Domains{}, fmt.Errorf("invalid DNS label from apps directory: %s", e.Name())
		}
		apps = append(apps, e.Name())
	}
	d := Domains{Apps: apps}
	for s := range services {
		d.Services = append(d.Services, s)
	}
	sort.Strings(d.Services)
	sort.Strings(d.Apps)
	return d, nil
}

// Routable reports whether the proxy can serve an apps/ directory.
func Routable(dir string) bool {
	for _, f := range []string{"index.php", "public/index.php", "public/index.html", "package.json"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err == nil {
			return true
		}
	}
	return false
}

// TestLabel extracts "name" from a URL whose host is name.test.
func TestLabel(raw string) (string, bool) {
	u, err := url.Parse(raw)
	if err != nil {
		return "", false
	}
	host := u.Hostname()
	label, ok := strings.CutSuffix(host, ".test")
	if !ok || !labelRE.MatchString(label) {
		return "", false
	}
	return label, true
}

// Block renders the managed block, newline-terminated.
func Block(d Domains, address string) string {
	var b strings.Builder
	b.WriteString(BeginMarker + "\n")
	b.WriteString("# Generated by devarch hosts sync; rerun to refresh.\n")
	writeDomains(&b, "Infrastructure services", d.Services, address)
	writeDomains(&b, "Development applications", d.Apps, address)
	b.WriteString("# Development tools\n" + address + " devarch.test\n")
	b.WriteString(EndMarker + "\n")
	return b.String()
}

func writeDomains(b *strings.Builder, heading string, labels []string, address string) {
	b.WriteString("# " + heading + "\n")
	for i := 0; i < len(labels); i += perLine {
		b.WriteString(address)
		for _, l := range labels[i:min(i+perLine, len(labels))] {
			b.WriteString(" " + l + ".test")
		}
		b.WriteString("\n")
	}
}

// ValidateAddress accepts dotted-quad IPv4 addresses only.
func ValidateAddress(address string) error {
	ip := net.ParseIP(address)
	if ip == nil || ip.To4() == nil || strings.Count(address, ".") != 3 {
		return errors.New("address must be an IPv4 address")
	}
	return nil
}

// ValidateHostname accepts lowercase DNS names with at least two labels.
func ValidateHostname(name string) error {
	if !hostnameRE.MatchString(name) {
		return errors.New("hostname must be a lowercase DNS name with at least two labels")
	}
	return nil
}

// ErrMarkers reports a hosts file with unmatched or duplicate markers.
var ErrMarkers = errors.New("hosts file contains malformed or duplicate DevArch managed-block markers")

// ReplaceBlock returns content with the managed block replaced, or appended
// after a blank line when absent. Content outside the markers is untouched.
func ReplaceBlock(content, block string) (string, error) {
	lines := strings.SplitAfter(content, "\n")
	if lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	begin, end := -1, -1
	for i, l := range lines {
		switch strings.TrimRight(l, "\r\n") {
		case BeginMarker:
			if begin >= 0 {
				return "", ErrMarkers
			}
			begin = i
		case EndMarker:
			if end >= 0 {
				return "", ErrMarkers
			}
			end = i
		}
	}
	switch {
	case begin < 0 && end < 0:
		if content == "" {
			return block, nil
		}
		if !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		return content + "\n" + block, nil
	case begin < 0 || end < 0 || end < begin:
		return "", ErrMarkers
	}
	return strings.Join(lines[:begin], "") + block + strings.Join(lines[end+1:], ""), nil
}

// CurrentBlock returns the managed block in content, or "" when absent.
func CurrentBlock(content string) string {
	content = normalize(content)
	i := strings.Index(content, BeginMarker+"\n")
	if i < 0 {
		return ""
	}
	j := strings.Index(content[i:], EndMarker)
	if j < 0 {
		return ""
	}
	return content[i : i+j+len(EndMarker)+1]
}

// Mapped returns every hostname mapped (to any address) in content.
func Mapped(content string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(normalize(content), "\n") {
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		f := strings.Fields(line)
		for _, name := range f[min(1, len(f)):] {
			if _, seen := out[strings.ToLower(name)]; !seen {
				out[strings.ToLower(name)] = f[0]
			}
		}
	}
	return out
}

// Register idempotently maps name to address: an existing canonical line
// (exactly one occurrence, alone on a line with that address) is left alone;
// otherwise the name is removed from every line and appended once.
func Register(content, name, address string) (string, bool) {
	occurrences, canonical := 0, 0
	for _, line := range strings.Split(normalize(content), "\n") {
		body := line
		if i := strings.IndexByte(body, '#'); i >= 0 {
			body = body[:i]
		}
		f := strings.Fields(body)
		if len(f) < 2 {
			continue
		}
		matches := 0
		for _, a := range f[1:] {
			if strings.EqualFold(a, name) {
				matches++
			}
		}
		occurrences += matches
		if matches == 1 && len(f) == 2 && f[0] == address {
			canonical++
		}
	}
	if occurrences == 1 && canonical == 1 {
		return content, false
	}
	out := Unregister(content, name)
	if out != "" && !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return out + address + "\t" + name + "\n", true
}

// Unregister removes name from every mapping line. Lines left without aliases
// are dropped, keeping a trailing comment if they had one.
func Unregister(content, name string) string {
	lines := strings.SplitAfter(content, "\n")
	var b strings.Builder
	for _, raw := range lines {
		line := strings.TrimRight(raw, "\r\n")
		eol := raw[len(line):]
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			b.WriteString(raw)
			continue
		}
		body, comment := line, ""
		if i := strings.IndexByte(line, '#'); i >= 0 {
			body, comment = line[:i], line[i:]
		}
		f := strings.Fields(body)
		var keep []string
		found := false
		for _, a := range f[min(1, len(f)):] {
			if strings.EqualFold(a, name) {
				found = true
			} else {
				keep = append(keep, a)
			}
		}
		switch {
		case !found:
			b.WriteString(raw)
		case len(keep) > 0:
			b.WriteString(f[0] + "\t" + strings.Join(keep, "\t"))
			if comment != "" {
				b.WriteString(" " + comment)
			}
			b.WriteString(eol)
		case comment != "":
			b.WriteString(comment + eol)
		}
	}
	return b.String()
}

func normalize(content string) string {
	content = strings.TrimPrefix(content, "\ufeff")
	return strings.ReplaceAll(content, "\r\n", "\n")
}

// Platform says which hosts file the browser uses.
type Platform string

const (
	Unix    Platform = "unix"
	Windows Platform = "windows"
)

// DetectPlatform honours DEVARCH_HOSTS_PLATFORM, then detects WSL/MSYS/Cygwin.
func DetectPlatform() Platform {
	switch Platform(os.Getenv("DEVARCH_HOSTS_PLATFORM")) {
	case Unix:
		return Unix
	case Windows:
		return Windows
	}
	if runtime.GOOS == "windows" || IsWSL() {
		return Windows
	}
	return Unix
}

// IsWSL reports whether this is a WSL kernel.
func IsWSL() bool {
	data, err := os.ReadFile("/proc/sys/kernel/osrelease")
	return err == nil && bytes.Contains(bytes.ToLower(data), []byte("microsoft"))
}

// Manager reads and writes the platform hosts file.
type Manager struct {
	Platform Platform
	// File is the Unix hosts file ($HOSTS_FILE, default /etc/hosts).
	File string
	// WindowsFile is the Windows hosts file as seen from this system.
	WindowsFile string
	// ScriptDir receives the PowerShell helpers on Windows platforms.
	ScriptDir string
	Runner    runner.Runner
}

// NewManager detects the platform and file locations.
func NewManager(r runner.Runner, scriptDir string) *Manager {
	m := &Manager{Platform: DetectPlatform(), File: "/etc/hosts", Runner: r, ScriptDir: scriptDir,
		WindowsFile: "/mnt/c/Windows/System32/drivers/etc/hosts"}
	if f := os.Getenv("HOSTS_FILE"); f != "" {
		m.File = f
	}
	if runtime.GOOS == "windows" {
		m.WindowsFile = filepath.Join(os.Getenv("SystemRoot"), "System32", "drivers", "etc", "hosts")
	}
	return m
}

// Path is the hosts file that matters for the browser.
func (m *Manager) Path() string {
	if m.Platform == Windows {
		return m.WindowsFile
	}
	return m.File
}

// Read returns the hosts file content.
func (m *Manager) Read() (string, error) {
	data, err := os.ReadFile(m.Path())
	return string(data), err
}

// Result describes a hosts update.
type Result struct {
	Changed bool
	Path    string
}

// Sync writes the managed block.
func (m *Manager) Sync(ctx context.Context, block string) (Result, error) {
	if m.Platform == Windows {
		return m.powershell(ctx, "sync-hosts.ps1", "-BlockBase64", base64.StdEncoding.EncodeToString([]byte(block)))
	}
	content, err := m.Read()
	if err != nil {
		return Result{}, fmt.Errorf("hosts file not found: %w", err)
	}
	updated, err := ReplaceBlock(content, block)
	if err != nil {
		return Result{}, err
	}
	return m.write(ctx, content, updated)
}

// Add maps one hostname.
func (m *Manager) Add(ctx context.Context, name, address string) (Result, error) {
	if m.Platform == Windows {
		return m.powershell(ctx, "register-host.ps1", "-HostName", name, "-Address", address)
	}
	content, err := m.Read()
	if err != nil {
		return Result{}, err
	}
	updated, _ := Register(content, name, address)
	return m.write(ctx, content, updated)
}

// Remove unmaps one hostname (Unix hosts files only).
func (m *Manager) Remove(ctx context.Context, name string) (Result, error) {
	if m.Platform == Windows {
		return Result{}, errors.New("removing a single Windows hosts entry is not supported; edit the file or rerun devarch hosts sync")
	}
	content, err := m.Read()
	if err != nil {
		return Result{}, err
	}
	return m.write(ctx, content, Unregister(content, name))
}

func (m *Manager) write(ctx context.Context, before, after string) (Result, error) {
	res := Result{Path: m.File}
	if before == after {
		return res, nil
	}
	res.Changed = true
	// Write in place rather than renaming: /etc/hosts is often a bind mount.
	if f, err := os.OpenFile(m.File, os.O_WRONLY|os.O_TRUNC, 0); err == nil {
		_, werr := f.WriteString(after)
		if cerr := f.Close(); werr == nil {
			werr = cerr
		}
		return res, werr
	}
	if _, err := exec.LookPath("sudo"); err != nil {
		return res, fmt.Errorf("administrator access is required to update %s (sudo not found)", m.File)
	}
	return res, m.Runner.Run(ctx, runner.Cmd{
		Name: "sudo", Args: []string{"tee", m.File},
		Stdin: strings.NewReader(after), Stdout: discard{},
	})
}

type discard struct{}

func (discard) Write(p []byte) (int, error) { return len(p), nil }

func (m *Manager) powershell(ctx context.Context, script string, args ...string) (Result, error) {
	res := Result{Path: m.WindowsFile}
	before, _ := os.ReadFile(m.WindowsFile)
	exe, err := findPowerShell()
	if err != nil {
		return res, err
	}
	scriptPath, err := m.installScript(script)
	if err != nil {
		return res, err
	}
	cmd := runner.Cmd{Name: exe, Args: append([]string{"-NoProfile", "-ExecutionPolicy", "Bypass", "-File", scriptPath}, args...)}
	if IsWSL() {
		if _, err := os.Stat("/init"); err == nil {
			// Use WSL's interop host so third-party binfmt handlers (notably Wine)
			// cannot intercept the Windows executable.
			cmd = runner.Cmd{Name: "/init", Args: append([]string{exe}, cmd.Args...)}
		}
	}
	if err := m.Runner.Run(ctx, cmd); err != nil {
		return res, err
	}
	after, _ := os.ReadFile(m.WindowsFile)
	res.Changed = !bytes.Equal(before, after)
	return res, nil
}

func findPowerShell() (string, error) {
	if p, err := exec.LookPath("powershell.exe"); err == nil {
		return p, nil
	}
	const fallback = "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
	if _, err := os.Stat(fallback); err == nil {
		return fallback, nil
	}
	return "", errors.New("powershell.exe is required to update the Windows hosts file")
}

// installScript writes the embedded helper to ScriptDir and returns the path
// PowerShell should open (a Windows path under WSL/Cygwin).
func (m *Manager) installScript(name string) (string, error) {
	data, err := windowsScripts.ReadFile("windows/" + name)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(m.ScriptDir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(m.ScriptDir, name)
	if existing, err := os.ReadFile(path); err != nil || !bytes.Equal(existing, data) {
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return "", err
		}
	}
	for _, conv := range []string{"wslpath", "cygpath"} {
		if _, err := exec.LookPath(conv); err == nil {
			out, err := exec.Command(conv, "-w", path).Output()
			if err == nil {
				return strings.TrimSpace(string(out)), nil
			}
		}
	}
	return path, nil
}
