package hosts

import (
	"context"
	"encoding/base64"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/prospect-ogujiuba/devarch/cli/internal/catalog"
	"github.com/prospect-ogujiuba/devarch/cli/internal/runner"
	"github.com/prospect-ogujiuba/devarch/cli/internal/testutil"
)

// Ported from scripts/hosts/sync-hosts.test.sh.
func discoverFixture(t *testing.T) (*catalog.Catalog, string, string) {
	t.Helper()
	repo := t.TempDir()
	lib := filepath.Join(repo, "services-library")
	testutil.WriteFiles(t, lib, map[string]string{
		"data/redis/compose.yml": "services:\n  redis:\n    container_name: redis\n",
		"web/nginx/compose.yml": `x-devarch:
  urls: [https://npm.test, https://example.com, http://adminer.test:8080/path]
services:
  nginx:
    container_name: "nginx-proxy-manager"
  duplicate:
    container_name: redis # duplicate is intentional
`,
	})
	apps := filepath.Join(repo, "apps")
	testutil.WriteFiles(t, apps, map[string]string{
		"alpha/public/index.php":             "",
		"beta/package.json":                  "{}",
		"not-routable/README.md":             "",
		".devarch-backups/ignored/index.php": "",
	})
	c, problems := catalog.Load([]catalog.Path{{Dir: lib}})
	if len(problems) > 0 {
		t.Fatal(problems)
	}
	return c, apps, lib
}

const fixtureHosts = "127.0.0.1 localhost\n# unrelated comment\n192.0.2.10 retained.test\n"

func TestSyncCreatesBlockAndIsIdempotent(t *testing.T) {
	c, apps, _ := discoverFixture(t)
	d, err := Discover(c, apps)
	if err != nil {
		t.Fatal(err)
	}
	block := Block(d, DefaultAddress)
	got, err := ReplaceBlock(fixtureHosts, block)
	if err != nil {
		t.Fatal(err)
	}
	want := fixtureHosts + `
# BEGIN DEVARCH HOSTS
# Generated by devarch hosts sync; rerun to refresh.
# Infrastructure services
127.0.0.1 adminer.test nginx-proxy-manager.test npm.test redis.test
# Development applications
127.0.0.1 alpha.test beta.test
# Development tools
127.0.0.1 devarch.test
# END DEVARCH HOSTS
`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
	again, err := ReplaceBlock(got, block)
	if err != nil || again != got {
		t.Fatalf("re-sync changed a current file: %v\n%s", err, again)
	}
	if d.Count() != 7 {
		t.Fatalf("count = %d", d.Count())
	}
}

func TestSyncRefreshesBlockAndKeepsOutsideContent(t *testing.T) {
	old := fixtureHosts + "\n" + BeginMarker + "\n127.0.0.1 stale.test\n" + EndMarker + "\n# after\n"
	got, err := ReplaceBlock(old, Block(Domains{Services: []string{"fresh"}}, DefaultAddress))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(got, "stale.test") || !strings.Contains(got, "127.0.0.1 fresh.test\n") ||
		!strings.HasPrefix(got, fixtureHosts) || !strings.HasSuffix(got, EndMarker+"\n# after\n") {
		t.Fatalf("got:\n%s", got)
	}
}

func TestSyncWrapsSixPerLine(t *testing.T) {
	b := Block(Domains{Services: []string{"a", "b", "c", "d", "e", "f", "g"}}, "10.0.0.1")
	if !strings.Contains(b, "10.0.0.1 a.test b.test c.test d.test e.test f.test\n10.0.0.1 g.test\n") {
		t.Fatal(b)
	}
}

func TestInvalidContainerNameFails(t *testing.T) {
	lib := t.TempDir()
	testutil.WriteFiles(t, lib, map[string]string{"bad/invalid/compose.yml": "services:\n  bad:\n    container_name: Bad_Name\n"})
	c, _ := catalog.Load([]catalog.Path{{Dir: lib}})
	if _, err := Discover(c, filepath.Join(lib, "none")); err == nil {
		t.Fatal("invalid container_name accepted")
	}
}

func TestMalformedMarkersFailSafely(t *testing.T) {
	for _, content := range []string{
		BeginMarker + "\nunterminated\n",
		EndMarker + "\n",
		EndMarker + "\n" + BeginMarker + "\n",
		BeginMarker + "\n" + EndMarker + "\n" + BeginMarker + "\n" + EndMarker + "\n",
	} {
		if _, err := ReplaceBlock(content, Block(Domains{Services: []string{"x"}}, DefaultAddress)); err != ErrMarkers {
			t.Errorf("accepted %q: %v", content, err)
		}
	}
}

func TestReplaceBlockEdgeCases(t *testing.T) {
	block := Block(Domains{Services: []string{"x"}}, DefaultAddress)
	if got, _ := ReplaceBlock("", block); got != block {
		t.Fatalf("empty file: %q", got)
	}
	if got, _ := ReplaceBlock("127.0.0.1 localhost", block); got != "127.0.0.1 localhost\n\n"+block {
		t.Fatalf("no trailing newline: %q", got)
	}
}

// Ported from scripts/hosts/register-host.test.sh.
const registerFixture = "127.0.0.1    localhost\n::1  localhost ip6-localhost\n192.0.2.10    demo.test    retained.test    # local aliases\n# keep this comment\n"

func TestRegister(t *testing.T) {
	got, changed := Register(registerFixture, "moneytrees.test", DefaultAddress)
	if !changed || got != registerFixture+"127.0.0.1\tmoneytrees.test\n" {
		t.Fatalf("adding a new hostname reformatted existing lines:\n%s", got)
	}
	if again, changed := Register(got, "moneytrees.test", DefaultAddress); changed || again != got {
		t.Fatal("re-registering a canonical mapping changed the file")
	}
	got, _ = Register(got, "demo.test", DefaultAddress)
	if !strings.Contains(got, "\n127.0.0.1\tdemo.test\n") ||
		!strings.Contains(got, "\n192.0.2.10\tretained.test # local aliases\n") ||
		!strings.HasPrefix(got, "127.0.0.1    localhost\n") {
		t.Fatalf("moving demo.test:\n%s", got)
	}
	if again, changed := Register(got, "demo.test", DefaultAddress); changed || strings.Count(again, "demo.test") != 1 {
		t.Fatal("re-registering an updated mapping changed the file")
	}
}

func TestUnregister(t *testing.T) {
	in := "127.0.0.1 only.test # gone\n127.0.0.1 a.test only.test b.test\n# only.test in a comment\n"
	want := "# gone\n127.0.0.1\ta.test\tb.test\n# only.test in a comment\n"
	if got := Unregister(in, "only.test"); got != want {
		t.Fatalf("got %q", got)
	}
}

func TestMappedAndCurrentBlockHandleBOMAndCRLF(t *testing.T) {
	content := "\ufeff127.0.0.1 localhost\r\n" + strings.ReplaceAll(Block(Domains{Services: []string{"redis"}}, DefaultAddress), "\n", "\r\n")
	m := Mapped(content)
	if m["redis.test"] != DefaultAddress || m["localhost"] != DefaultAddress || m["devarch.test"] == "" {
		t.Fatalf("mapped = %v", m)
	}
	if !strings.HasPrefix(CurrentBlock(content), BeginMarker+"\n") {
		t.Fatalf("block = %q", CurrentBlock(content))
	}
}

func TestValidation(t *testing.T) {
	for _, a := range []string{"999.1.1.1", "1.2.3", "::1", "x"} {
		if ValidateAddress(a) == nil {
			t.Errorf("accepted address %q", a)
		}
	}
	if ValidateAddress("192.0.2.10") != nil {
		t.Error("rejected valid address")
	}
	for _, h := range []string{"unsafe host.test", "single", "UPPER.test", "-bad.test"} {
		if ValidateHostname(h) == nil {
			t.Errorf("accepted hostname %q", h)
		}
	}
}

func TestManagerUnixWritesInPlace(t *testing.T) {
	file := filepath.Join(t.TempDir(), "hosts")
	os.WriteFile(file, []byte(fixtureHosts), 0o644)
	f := &runner.Fake{}
	m := &Manager{Platform: Unix, File: file, Runner: f}
	res, err := m.Sync(context.Background(), Block(Domains{Services: []string{"x"}}, DefaultAddress))
	if err != nil || !res.Changed {
		t.Fatalf("%+v %v", res, err)
	}
	if res, _ = m.Sync(context.Background(), Block(Domains{Services: []string{"x"}}, DefaultAddress)); res.Changed {
		t.Fatal("second sync reported a change")
	}
	if _, err := m.Add(context.Background(), "demo.test", DefaultAddress); err != nil {
		t.Fatal(err)
	}
	if _, err := m.Remove(context.Background(), "demo.test"); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(file)
	if strings.Contains(string(data), "demo.test") || !strings.Contains(string(data), "x.test") || len(f.Cmds) != 0 {
		t.Fatalf("file:\n%s\ncmds: %v", data, f.Lines())
	}
}

// The embedded PowerShell helpers keep their own encoding and line-ending
// behaviour; exercise them against a fixture when PowerShell is reachable.
func TestWindowsHelpersAgainstFixture(t *testing.T) {
	ps, err := findPowerShell()
	if err != nil {
		t.Skip("powershell.exe not available")
	}
	if _, err := exec.LookPath("wslpath"); err != nil {
		t.Skip("wslpath not available")
	}
	dir := t.TempDir()
	m := &Manager{ScriptDir: dir}
	run := func(script string, args ...string) {
		t.Helper()
		path, err := m.installScript(script)
		if err != nil {
			t.Fatal(err)
		}
		argv := append([]string{ps, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", path}, args...)
		// Under WSL, go through the interop host as Manager.powershell does.
		name := "/init"
		if _, err := os.Stat("/init"); err != nil || !IsWSL() {
			name, argv = argv[0], argv[1:]
		}
		if out, err := exec.Command(name, argv...).CombinedOutput(); err != nil {
			t.Fatalf("%s: %v\n%s", script, err, out)
		}
	}
	winPath := func(p string) string {
		out, err := exec.Command("wslpath", "-w", p).Output()
		if err != nil {
			t.Fatal(err)
		}
		return strings.TrimSpace(string(out))
	}

	fixture := filepath.Join(dir, "windows-hosts")
	original := "# comment\r\n127.0.0.1    first.test    second.test\r\n"
	os.WriteFile(fixture, []byte(original), 0o644)
	run("register-host.ps1", "-HostName", "moneytrees.test", "-HostsPath", winPath(fixture))
	data, _ := os.ReadFile(fixture)
	if string(data) != original+"127.0.0.1\tmoneytrees.test\r\n" {
		t.Fatalf("register reformatted the file: %q", data)
	}

	block := Block(Domains{Services: []string{"redis"}}, DefaultAddress)
	run("sync-hosts.ps1", "-BlockBase64", base64.StdEncoding.EncodeToString([]byte(block)), "-HostsPath", winPath(fixture))
	data, _ = os.ReadFile(fixture)
	if !strings.Contains(string(data), "\r\n# BEGIN DEVARCH HOSTS\r\n") || !strings.Contains(string(data), "127.0.0.1 redis.test\r\n") {
		t.Fatalf("sync output: %q", data)
	}
}
